Add intro-lceture-1
SemyonSinchenko/qmlcourse pull request #109
Opened 2021-07-28 16:21 UTC by SemyonSinchenko

Короче лекция должна быть чистым завлекаловом.
В теории, ее же хочется на Хабр, для раскрутки курса.

Я часто бываю на Хабре и слежу кто что спрашивает в комментах про "квантовые"
статьи. Ну и постарался собрать тут популярные ответы, а также максимально
завлечь людей.

По поводу цвета - голубой, так как серый смотрелся уныло. Но все обсуждаемо.

On branch semyonsinchenko-scipop-intro-1
Changes to be committed:

- modified:   qmlcourseRU/_static/index/program.plantuml
- modified:   qmlcourseRU/_static/index/program.png
- new file:   qmlcourseRU/_static/intro1block/intro1/Bitcoin.jpg
- new file:   qmlcourseRU/_static/intro1block/intro1/Feinman.jpg
- new file:   qmlcourseRU/_static/intro1block/intro1/Moores_Law.png
- new file:   qmlcourseRU/_static/intro1block/intro1/Preskill.jpg
- new file:   qmlcourseRU/_static/intro1block/intro1/Salesman.png
- new file:   qmlcourseRU/_static/intro1block/intro1/Schrodinger.jpg
- new file:   qmlcourseRU/_static/intro1block/intro1/quantum_computer.jpg
- modified:   qmlcourseRU/_toc.yml
- modified:   qmlcourseRU/book/acknowledgments.md
- new file:   qmlcourseRU/book/intro1block/intro1.md

Close #108

2021-07-28 16:50 UTC, Randl commented on qmlcourseRU/book/intro1block/intro1.md
> +Здесь я не зря написал "скорее всего". Дело в том, что этот вопрос является одним из [так называемых вопросов тысячилетия](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B2%D0%B5%D0%BD%D1%81%D1%82%D0%
```suggestion
Здесь я не зря написал "скорее всего". Дело в том, что этот вопрос является одним из [так называемых вопросов тысячелетия](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B2%D0%B5%D0%BD%D1%81%D1%82%D0%B2%D0%BE_%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%BE%D0%B2_P_%D0%B8_NP). Так, для известной задачи о наполнении рюкзака, мы не занем сегодня эффективного алгоритма решения на классическом компьютере. Но мы также и не можем пока доказать, что такого алгоритма не существует. Ну то есть скорее всего такого алгоритма и правда не существует, а также скорее всего $P \neq NP$, но доказать это пока ни у кого не вышло. Но это скорее лирическое отступление.
```

2021-07-28 16:50 UTC, Randl commented on qmlcourseRU/book/intro1block/intro1.md
> +Так вот, дело в том, что для квантовых компьютеров уже сегодня известны алгоритмы, которые позволяют решать задачи из класса таких трудно разрешимых на классических компьютерах. Вероятно, самым извес
Все таки факторизация не NP-полная задача, и в целом NP сложные на квантовом компе точно эффективно не решаются

2021-07-28 16:50 UTC, Randl commented on qmlcourseRU/book/intro1block/intro1.md
> +- рекорд в точных и масштабируемых, но очень трудно программируемых компьютерах это $\sim 25$ кубит
- рекорд в точных, масштабируемых, легко программируемых (топологические) это 0 кубитов 

(извините)

2021-07-28 17:01 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +Так вот, дело в том, что для квантовых компьютеров уже сегодня известны алгоритмы, которые позволяют решать задачи из класса таких трудно разрешимых на классических компьютерах. Вероятно, самым извес
Да, верно, спасибо! Надо подумать как это перефразировать, при этом не углубляясь в суть факторизации, чтобы с простыми примерами...

2021-07-28 18:29 UTC, vtrokhymenko commented on qmlcourseRU/book/intro1block/intro1.md
> +Так называемый закGон Мура, сформулированный Гордоном Муром еще в конце 60-х годов, говорит нам о том, что число транзисторов будет удваиваться каждый год. И этот закон стабильно выполняется.
```suggestion
Так называемый закон Мура, сформулированный Гордоном Муром еще в конце 60-х годов, говорит нам о том, что число транзисторов будет удваиваться каждый год. И этот закон стабильно выполняется.
```

2021-07-28 19:07 UTC, vtrokhymenko commented
хотелось бы ещё поговорить о рублях, то есть сколько стоит поставить, поддерживать и когда можно будет его носить в кармане?

2021-07-28 21:42 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +- рекорд в точных и масштабируемых, но очень трудно программируемых компьютерах это $\sim 25$ кубит
Добавил

2021-07-28 21:43 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +Так вот, дело в том, что для квантовых компьютеров уже сегодня известны алгоритмы, которые позволяют решать задачи из класса таких трудно разрешимых на классических компьютерах. Вероятно, самым извес
Исправил.

2021-07-28 21:56 UTC, SemyonSinchenko commented
> хотелось бы ещё поговорить о рублях, то есть сколько стоит поставить, поддерживать и когда можно будет его носить в кармане?

Добавил

2021-07-30 09:10 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +Так называемый закон Мура, сформулированный Гордоном Муром еще в конце 60-х годов, говорит нам о том, что число транзисторов будет удваиваться каждый год. И этот закон стабильно выполняется.
каждые два года, а не год. И лучше уточнить, что не просто число транзисторов (вообще во Вселенной), а число транзисторов, размещаемых на кристалле интегральной схемы

2021-07-30 09:11 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +За последние 10-15 лет машинное обучение достигло поистине небывалых высот в своем развитии. Многие задачи, решение которых силами компьютера, раньше казалось невозможным сегодня успешно решаются при
> Так, наиболее масштабные искусственные нейронные сети имеют сегодня порядка 15 миллионов нейронов , в то время как человеческий мозг имеет порядка 85 миллиардов!

Не стоит тут сравнивать "нейроны" и нейроны. Аналогия не очень здоровая. К тому же, в последних языковых моделях уже триллионы параметров.

2021-07-30 09:12 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +И тут тоже на помощь могут прийти квантовые компьютеры. В данном случае, квантовые аналоги нейронных сетей, а также их комбинации с классическими нейронными сетями уже сегодня показывают впечатляющие
> Так, есть работы, где показано
Можно ссылочку

2021-07-30 09:14 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +### Сколько нужно кубит под разные задачи?
Множественное – "кубитов" же. Мужской род.
Некая [ссылка](http://aztekium.pl/find.py?szukaj=%D0%BA%D1%83%D0%B1%D0%B8%D1%82%D1%8B&lang=ru) со склонением этого слова

2021-07-30 09:16 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +- Задачи оптимизации: $\sim 100 \cdot 10^3$ (10 тысяч) кубит
100 тысяч

2021-07-30 09:22 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +Так что когда кто-то заявляет о достижении квантового превосходства, то это важный повод в среде ученых и разработчиков квантовых компьютеров, но скорее всего это очень малозначимый факт, с точки зре
> важный повод в среде 
Похоже на кальку с английского. В русском повод – всегда _для_ чего-то

2021-07-30 09:23 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +Квантовое превосходство это решение на квантовом компьютере задачи, которую нельзя решить на классическом компьютере за разумное время (10 тысяч лет разумным временем не считается). Достижение кванто
Тут хотелось бы разобрать реальную историю с заявлением о квантовом превосходстве и соотв. нюансах. Или хотя бы ссылку дать

2021-07-30 09:25 UTC, Yorko commented on qmlcourseRU/book/intro1block/intro1.md
> +В общем сейчас идет довольно интересный процесс войны меча и щита. Пока одни ученые строят более мощные квантовые компьютеры, другие придумывают более продвинутые алгоритмы их симуляции. Хотя конечно
> интересный процесс войны меча и щита.

Не очень точная аналогия. Вот алгоритм Шора и криптозащита – это меч и щит, да. А классические и квантовые компы – скорее две скаковые лошади.

2021-07-30 09:28 UTC, Yorko requested changes
Отличная лекция, для вводной – что надо!

2021-07-30 09:29 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +За последние 10-15 лет машинное обучение достигло поистине небывалых высот в своем развитии. Многие задачи, решение которых силами компьютера, раньше казалось невозможным сегодня успешно решаются при
Цифра в 15 миллионов взята из какой-то публикации (в чем-то рецензируемом) с названием типа "Estimation the number of neurons in modern neural networks". Типа они параметры примерно перевели в количество нейронов. Триллион параметров ведь можно получить и на одном нейроне просто имея вектор входа размерности триллион. Все же хочется дать тут какое-то сравнение. Могу перефразировать, если есть идеи как. Но сам абзац хотел бы сохранить...

2021-07-30 09:30 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +И тут тоже на помощь могут прийти квантовые компьютеры. В данном случае, квантовые аналоги нейронных сетей, а также их комбинации с классическими нейронными сетями уже сегодня показывают впечатляющие
Это надо у @magnus-the-collectioner спрашивать, он рассказывал на дата-фесте)

2021-07-30 09:31 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +### Сколько нужно кубит под разные задачи?
Поправлю тут, но справедливости ради со склонением этого слова бардак по всему курсу...

2021-07-30 09:32 UTC, SemyonSinchenko commented on qmlcourseRU/book/intro1block/intro1.md
> +В общем сейчас идет довольно интересный процесс войны меча и щита. Пока одни ученые строят более мощные квантовые компьютеры, другие придумывают более продвинутые алгоритмы их симуляции. Хотя конечно
Это фраза @meandmytram из его доклада на Дата Фесте про тензорные сети. Можно перефразировать...

2021-07-30 11:19 UTC, vtrokhymenko approved these changes

2021-08-02 17:26 UTC, merged