Added spell checker and other
SemyonSinchenko/qmlcourse pull request #118
Opened 2021-07-31 09:27 UTC by dkorzhov

2021-07-31 10:42 UTC, vtrokhymenko commented
@dkorzhov спасибо
давай сделаем spell gh-action так, чтобы он не тормозил другие actions. пусть падает, но все остальное чтобы запускалось, сможешь?

2021-07-31 11:34 UTC, dkorzhov commented
> @dkorzhov спасибо
> давай сделаем spell gh-action так, чтобы он не тормозил другие actions. пусть падает, но все остальное чтобы запускалось, сможешь?

Можно сделать continue-on-error: true и тогда он будет всегда success, но ошибку можно будет посмотреть только в логах.

2021-07-31 12:15 UTC, vtrokhymenko reviewed
> > @dkorzhov спасибо
> > давай сделаем spell gh-action так, чтобы он не тормозил другие actions. пусть падает, но все остальное чтобы запускалось, сможешь?
> 
> Можно сделать continue-on-error: true и тогда он будет всегда success, но ошибку можно будет посмотреть только в логах.

оно отмечает зеленым job, и ошибки видно в `files changed`. хотелось чтобы было красным если нашло все же ошибки, но остальные запускались и не обращали внимание

2021-07-31 12:15 UTC, vtrokhymenko commented on .github/workflows/test-psi4-setup.yml
> +          publish_dir: ./qmlcourseRU
а зачем это тут? для сего ведь используется отдельный файл

2021-07-31 13:43 UTC, dkorzhov commented
> > > @dkorzhov спасибо
> > > давай сделаем spell gh-action так, чтобы он не тормозил другие actions. пусть падает, но все остальное чтобы запускалось, сможешь?
> > 
> > 
> > Можно сделать continue-on-error: true и тогда он будет всегда success, но ошибку можно будет посмотреть только в логах.
> 
> оно отмечает зеленым job, и ошибки видно в `files changed`. хотелось чтобы было красным если нашло все же ошибки, но остальные запускались и не обращали внимание

Так вроде изначально и было такое поведение, остальные джобы выполнялись, только сам pipelien потом становился красным. Как мы хотим эти проверки использовать дальше? В отдельном файле github actions или добавим в основной?

2021-07-31 13:44 UTC, dkorzhov commented
И по поводу теста на трех OS. Оставим в отдельном файле с ручным запуском? pre-commit для теста OS тогда тоже убираю?

2021-07-31 14:28 UTC, vtrokhymenko commented
>  Так вроде изначально и было такое поведение, остальные джобы выполнялись, только сам pipelien потом становился красным.
сейчас ведь `spell check` отображается зеленым, хотя ошибки есть согласно описанию actions
![image](https://user-images.githubusercontent.com/8581044/127742941-79b77be4-6b9d-49ab-82a3-54174da190ce.png)

> Как мы хотим эти проверки использовать дальше? В отдельном файле github actions или добавим в основной?

лучше в отдельном

2021-07-31 14:29 UTC, vtrokhymenko commented
> И по поводу теста на трех OS. Оставим в отдельном файле с ручным запуском?

для этого лучше в отдельном. 

> pre-commit для теста OS тогда тоже убираю?

получается что да, они должны запускаться только для лекций

2021-07-31 18:16 UTC, vtrokhymenko commented
выполнить ещё локально `pre-commit` и сделай commit изменений, дабы посмотреть всю картину

2021-08-01 09:45 UTC, SemyonSinchenko requested changes
Кажется надо довести словарь до хоть чуть-чуть разумного вида перед тем, как мержить. Мои правки, кажется, покроют самую боль про кубиты, гейты и прочее.

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "геймификаци.*",
```suggestion
      "геймификаци.*",
      "гейт.*",
      "Гейт.*",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "кроссфункциональн.*",
```suggestion
      "кроссфункциональн.*",
      ".*кубит.*",
      "Кубит.*",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "скоммуницируй",
```suggestion
      "скоммуницируй",
      ".*скори.*",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "хакатон.*",
```suggestion
      "хакатон.*",
      "хардкод.*",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "скринкаст.*",
```suggestion
      "скринкаст.*",
      "Слэтер.*",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "стриминг.*",
```suggestion
      "стриминг.*",
      "сэмпл.*",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "интранет.*",
```suggestion
      "интранет.*",
      "Йожи",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "токен.*",
```suggestion
      "токен.*",
      "топологически",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "МакКлелланда",
```suggestion
      "МакКлелланда",
      "масштабируемость",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "оффер",
```suggestion
      "оффер",
      "пайплайн.*",
      "параметризу.тся",
```

2021-08-01 09:45 UTC, SemyonSinchenko commented on .yaspellerrc.json
> +      "апдейт.*",
```suggestion
      "апдейт.*",
      "аппроксиматор.*",
```

2021-08-02 16:20 UTC, vtrokhymenko commented
@dkorzhov а можешь принять правки @SemyonSinchenko, а то вроде как они не добавились в соответствующие файлы?

2021-08-04 05:51 UTC, vtrokhymenko commented
@dkorzhov ping

2021-08-04 06:34 UTC, dkorzhov commented
> @dkorzhov ping

По поводу правок. Чуть позже сегодня закину.
Я там смотрел, не совсем понятно какие забирать. Из master ветки забрать правки? Так как в этой ветке в файлы внесены правки.

2021-08-04 06:37 UTC, vtrokhymenko commented
> > @dkorzhov ping
> 
> По поводу правок. Чуть позже сегодня закину.
> Я там смотрел, не совсем понятно какие забирать. Из master ветки забрать правки? Так как в этой ветке в файлы внесены правки.

речь о правках @SemyonSinchenko, которые он оставил (посмотри чуть выше)

2021-08-04 06:46 UTC, dkorzhov commented
> > > @dkorzhov ping
> > 
> > 
> > По поводу правок. Чуть позже сегодня закину.
> > Я там смотрел, не совсем понятно какие забирать. Из master ветки забрать правки? Так как в этой ветке в файлы внесены правки.
> 
> речь о правках @SemyonSinchenko, которые он оставил (посмотри чуть выше)

Да, я их видел. Только не могу сообразить, как я их могу к себе забрать. Github предлагает только fetch and merge с master. Я могу их только copy-past к себе сделать, только не пойму для чего так. То есть мы спокойно можем принять PR и сделать merge в master, а от туда я заберу все изменения к себе.
Или я чего то не уловил?

2021-08-04 06:49 UTC, SemyonSinchenko commented
> Или я чего то не уловил?

Точно, ты же в форке... Тогда давайте мержим так, а эти правки потом отдельно

2021-08-04 07:01 UTC, vtrokhymenko approved these changes

2021-08-04 07:03 UTC, SemyonSinchenko approved these changes

2021-08-04 08:44 UTC, vtrokhymenko commented
@SemyonSinchenko @dkorzhov тогда льем в master?

2021-08-04 15:41 UTC, merged