[WIP] initial l6 commit
SemyonSinchenko/qmlcourse pull request #124
Opened 2021-08-03 22:36 UTC by stalkermustang

2021-08-10 12:45 UTC, stalkermustang commented
D: что тут произошло

2021-08-12 08:44 UTC, Yorko commented
@stalkermustang вот теперь нормально мастера вмержил, сорян :)

2021-08-24 22:24 UTC, stalkermustang commented
![image](https://user-images.githubusercontent.com/26546178/130698029-f85288b3-dd12-4d44-9b55-8817ffaa87a8.png)
так и чиво как ето фиксить, чтобы уехали изменения?

2021-08-24 22:35 UTC, stalkermustang commented
можно смотреть/ревьюить

2021-08-25 05:06 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +В предыдущих уроках мы оперировали малым количеством переменных. Для каждого блока логики или примера кода вводилось 3-5 объектов, над которыми осуществлялись некоторые операции. Но что делать, если
«уроках» мб лучше «лекциях»?

2021-08-25 05:24 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +Часто в программах - даже в (квантовом) машинном обучении - приходится работать с большим количество __однотипных__ переменных. Специально при этого придуманы **массивы** (по-английски array). В Pyth
```suggestion
Часто в программах - даже в (квантовом) машинном обучении - приходится работать с большим количество __однотипных__ переменных. Специально для этого придуманы **массивы** (по-английски array). В Python их еще называют **списками** (list). В некоторых языках программирования эти понятия отличаются, но не в Python. Список может хранить переменные **разного** типа. Для создания простого списка необходимо указать квадратные скобки или вызвать конструктор типа (`list` - это отдельный тип, фактически такой же, как int или str), а затем перечислить **объекты через запятую**:
```

2021-08-25 05:24 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
здорово что упомянул это, было бы здорово написать ещё что вместо списка тогда использовать, дабы картина была целой

2021-08-25 05:27 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
не удобно смотреть на вывод, например, `print(math_journal)`, а когда такого добра больше 2х, то нужно пересмотреть код, дабы понять где оно было
как на счет исправить на `print(f"{math_journal = }")`

2021-08-25 05:30 UTC, vtrokhymenko commented
> ![image](https://user-images.githubusercontent.com/26546178/130698029-f85288b3-dd12-4d44-9b55-8817ffaa87a8.png)
> так и чиво как ето фиксить, чтобы уехали изменения?

пока живем так. поставили для того, чтобы вы сразу исправляли не правильно написанные слова. к концу добавим определенные слова в игнор, дабы все красилось в зелёный

2021-08-25 07:40 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
..а что можно использовать? я что-то сам повис на этом вопросе :D

2021-08-25 07:41 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
классы, дикты еще не проходили, а про таплы вообще не рассказывается :\

2021-08-25 09:10 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
да, кортежи используют для такого. если не рассказывал об этом не проблема, можно просто дать ссылку что почитать. всяко это будет лучше, чем просто осветить проблему без хоть какого-то решения

2021-08-25 11:55 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
даже не знал про такое, fixed

2021-08-25 12:16 UTC, stalkermustang commented
> лучше `print(f'Последняя оценка: {last_grade}')`: быстрее работает и удобнее читать
> и кавычки хорошо бы одного вида сделать, а то где-то `'`, а гдет-то `"` (по мне, то двойные правильнее)

это ж каждый раз шифт лишний нажимать...

2021-08-29 16:10 UTC, vtrokhymenko commented
* @stalkermustang будешь что-то добавлять или можно лить?
* @SemyonSinchenko сделай проверку хоть по диагонали

2021-08-29 17:11 UTC, stalkermustang commented
> * @stalkermustang будешь что-то добавлять или можно лить?
> * @SemyonSinchenko сделай проверку хоть по диагонали

я не думал доливать, всё тутки

2021-08-29 17:13 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
а тут будешь добавлять о кортеже?

2021-08-29 17:47 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l6.md
> +```
а блен( добавлю(

2021-08-30 09:25 UTC, SemyonSinchenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +5. Для проверки вхождения какого-либо объекта в список нужно использовать конструкцию `x_obj in some_list`, которая вернет `True`, если массив содержит `x_obj`, и `False` в ином случае.
Мож добавим, что b = a[:] это самый простой способ сделать копию списка и вообще, что модификация слайсов не меняет основной лист? Ну и что можно мемори оверхед словить, так как это копия?

2021-08-30 09:25 UTC, SemyonSinchenko approved these changes

2021-08-30 09:51 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l6.md
> +5. Для проверки вхождения какого-либо объекта в список нужно использовать конструкцию `x_obj in some_list`, которая вернет `True`, если массив содержит `x_obj`, и `False` в ином случае.
докину вечером

2021-08-31 14:08 UTC, Yorko requested changes
В целом хорошо, добавил пару комментариев.

2021-08-31 14:08 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
Такой принт не работает в Python 3.7, поэтому и вывода нет. Давай поменяем на `print(f"math_journal = {math_journal}")`, чтоб уж точно работало. 

Дело не только в синтаксисе, хочется в лекции видеть питонячий вывод, которого сейчас нет.

2021-08-31 14:08 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +- `list` -- это **объект-контейнер, который хранит другие объекты разных типов**. Запись происходит упорядочено и последовательно, а каждому объекту присвоен **целочисленный номер, начиная с нуля**;
Слово "контейнер" появляется первый раз в заключении

2021-08-31 14:26 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
f-строки вроде как появились ещё в py36. и как видно по снимку, то они работают
![image](https://user-images.githubusercontent.com/8581044/131520402-b21b7c83-1b03-418e-96f4-f0788967dedd.png)

и таким образом удобнее смотреть вывод и быстро понимать где это выполнилось

2021-09-07 11:26 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
f-строки – да, но конкретно этот синтаксис у меня в Python 3.7 не работает,  а в poetry у нас именно Python 3.7 и выше прописан.

2021-09-07 11:32 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
лучше тогда перейти на 3.8 уж. какая нашим студам разница, а нам удобнее

2021-09-07 11:34 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
Ладно, тогда тут аппрув, а переход на 3.8. надо будет отдельно обсудить с @dkorzhov

2021-09-07 11:35 UTC, Yorko approved these changes

2021-09-07 11:59 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +- `list` -- это **объект-контейнер, который хранит другие объекты разных типов**. Запись происходит упорядочено и последовательно, а каждому объекту присвоен **целочисленный номер, начиная с нуля**;
[тут](https://github.com/SemyonSinchenko/qmlcourse/blob/master/.github/workflows/pre-commit-deploy-book.yml) и [тут](https://github.com/SemyonSinchenko/qmlcourse/blob/master/.github/workflows/test-psi4-setup.yml) 3.8

2021-09-07 11:59 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
[тут](https://github.com/SemyonSinchenko/qmlcourse/blob/master/.github/workflows/pre-commit-deploy-book.yml) и [тут](https://github.com/SemyonSinchenko/qmlcourse/blob/master/.github/workflows/test-psi4-setup.yml) 3.8

2021-09-07 12:01 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +5. Для проверки вхождения какого-либо объекта в список нужно использовать конструкцию `x_obj in some_list`, которая вернет `True`, если массив содержит `x_obj`, и `False` в ином случае.
@stalkermustang  докинешь?

2021-09-07 12:07 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +print(f"{math_journal = }")
Добро, тогда в [pyproject.toml](https://github.com/SemyonSinchenko/qmlcourse/blob/master/pyproject.toml#L9) надо будет на "python = "^3.8" поправить.

2021-09-09 08:44 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +5. Для проверки вхождения какого-либо объекта в список нужно использовать конструкцию `x_obj in some_list`, которая вернет `True`, если массив содержит `x_obj`, и `False` в ином случае.
@stalkermustang

2021-09-13 20:06 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l6.md
> +5. Для проверки вхождения какого-либо объекта в список нужно использовать конструкцию `x_obj in some_list`, которая вернет `True`, если массив содержит `x_obj`, и `False` в ином случае.
@vtrokhymenko @SemyonSinchenko  так норм?

2021-09-13 20:18 UTC, SemyonSinchenko commented
Мержим?

2021-09-13 20:19 UTC, stalkermustang commented
> Мержим?

LESSSS GOOOOOO

2021-09-13 20:32 UTC, merged

2021-09-14 07:03 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l6.md
> +6. Самый простой способ сделать копию списка - это сделать срез по всему объекту: `my_list[:]`. Однако будьте внимательны -- в одних случаях копирование происходит полностью (по значению), а в некото
«в общем и целом» (с)