Initial version of a QNN lecture.
SemyonSinchenko/qmlcourse pull request #152
Opened 2021-08-31 16:04 UTC by magnus-the-collectioner

2021-08-31 16:17 UTC, vtrokhymenko commented
немного поспешил, ждем когда будет не черновик

2021-09-03 12:56 UTC, vtrokhymenko commented
@magnus-the-collectioner как обстоят дела?

2021-09-06 15:21 UTC, Yorko commented
ааа, черт, я что-то не так делаю, тащу изменения из других веток – пошел ботать Git.

В-общем, тут я добавил QNN в `_toc.yml` и внес пару мелких фиксов. 

Читается здорово, пока прям ревью рано делать, но некоторые места хотелось бы поподробнее. Может, пример дальше это пояснит

2021-09-07 09:42 UTC, Yorko commented
Где-то косяки пошли с мёржами (возможно, из-за меня тоже, надо проверить). В частности, правки к лекциям 4 и 5 по питону залиты (см. #139 и #140), но на данный момент их нет в мастере: [https://github.com/SemyonSinchenko/qmlcourse/tree/master/qmlcourseRU/book/pythonblock](https://github.com/SemyonSinchenko/qmlcourse/tree/master/qmlcourseRU/book/pythonblock). Так что вернул, и в этом PR они как новые файлы показываются.

2021-09-07 10:09 UTC, vtrokhymenko commented
после решения вопросов с #154 лишние лекции тут нужно будет убрать

2021-09-07 10:40 UTC, Yorko commented
Как #154 будет вмержен, эти файлы не должны будут в диффе показываться, т.к. будут и в этой ветке, и в мастере. В-общем, Никит, сорян, что в этой ветке устроил эту разборку, надо было сразу в отдельной.

2021-09-07 10:53 UTC, Yorko commented
Немного запутался, но норм, теперь лишних файлов в диффе нет

2021-09-12 07:35 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Схема обучения гибридной нейронной сети
Мы трепетно относимся к авторским правам, так что надо сюда вставить ссылку откуда взята картинка. Это из блога TFQ ведь, да?

2021-09-12 07:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Ansatz, соответствующий свёрточному слою нейронной сети в PennyLane
То же замечание про картинки - ссылку и качество получше. Можешь дать ссылки на картинки в комменты, а я уже сам попробую все аккуратно сделать?

2021-09-12 07:38 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как __ansatz__  -- по своей сути это заранее подготовленные участки параметрической схемы, которые
```suggestion
Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как __ansatz__  -- по своей сути это заранее подготовленные участки параметрической схемы, которые могут быть использованы как составные блоки сети. Если проводить параллели с классическим машинным обучением, то в рамках библиотеки `PennyLane` эти схемы называются __templates__ и могут представлять собой, например, свёрточный слой или эмбеддинг, но и более общие элементы квантовой схемы вроде подготовки состояний или перестановок между кубитами.
```

2021-09-12 07:41 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Функция потерь работает таким же образом, как и в полностью классических сетях, так как оптимизация происходит на классическом железе  -- единственное, что отличается, -- это объединение квантовых и
```suggestion
Функция потерь работает таким же образом, как и в полностью классических сетях, так как оптимизация происходит на классическом железе  -- единственное, что отличается, -- это объединение квантовых и классических градиентов. Градиент по нашей квантовой схеме получается при помощи замера состояния, которое может варьироваться из-за вероятностой природы кубита, поэтому несколько замеров позволяют аппроксимировать ожидаемый градиент при помощи методов вроде finite differences или [parameter shift](hogradients), после чего остаётся только совместить его с классическим.
```

2021-09-12 07:42 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Оценить ошибку, рассчитать градиенты и обновить параметры.
```suggestion
 - Трансформировать данные из классических в квантовые операторы;
 - Отправить эти данные для вычисления на квантовой схеме;
 - Просэмплировать и замерить результат квантовой схемы;
 - Отправить результаты для вычисления на классической схеме;
 - Оценить ошибку, рассчитать градиенты и обновить параметры.
```

2021-09-12 07:42 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Трансформировать данные из классических в квантовые операторы;
```suggestion
 - Трансформировать данные из классических в квантовые операторы;
```

2021-09-12 07:42 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Отправить эти данные для вычисления на квантовой схеме;
```suggestion
 - Отправить эти данные для вычисления на квантовой схеме;
```

2021-09-12 07:42 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Просэмплировать и замерить результат квантовой схемы;
```suggestion
 - Просэмплировать и замерить результат квантовой схемы;
```

2021-09-12 07:43 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Отправить результаты для вычисления на классической схеме;
```suggestion
 - Отправить результаты для вычисления на классической схеме;
```

2021-09-12 07:43 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Оценить ошибку, рассчитать градиенты и обновить параметры.
```suggestion
 - Оценить ошибку, рассчитать градиенты и обновить параметры.
```

2021-09-12 07:43 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- В ближайшие годы полностью квантовые нейронные сети не смогут решать задачи целиком, поэтому будут использоваться в качестве составляющей гибридного квантово-классического решения.
```suggestion
 - В ближайшие годы полностью квантовые нейронные сети не смогут решать задачи целиком, поэтому будут использоваться в качестве составляющей гибридного квантово-классического решения.
```

2021-09-12 07:43 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Обучение подобных сетей практически идентично обучению классических сетей за исключением нескольких трюков, необходимых для работы с параметрами квантовых схем.
```suggestion
 - Обучение подобных сетей практически идентично обучению классических сетей за исключением нескольких трюков, необходимых для работы с параметрами квантовых схем.
```

2021-09-12 07:44 UTC, SemyonSinchenko requested changes
В целом круто, только по мелочи поправить местами и все.

2021-09-12 08:43 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +Схема обучения гибридной нейронной сети
Это картинка из пэйпера TFQ, недавно знакомый кофаундер TFQ запаблишил вторую версию - там должны быть обе, можно попробовать из достать в лучшем резолюшене оттуда. https://arxiv.org/pdf/2003.02989.pdf

2021-09-12 08:45 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +Ansatz, соответствующий свёрточному слою нейронной сети в PennyLane
Ansatz из документации Xanadu по PennyLane, так как мы в основном работаем с ним, но я бы взял просто любой Ansatz, потому что этот в таком себе разрешении и в документации. https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.CVNeuralNetLayers.html

2021-09-12 08:46 UTC, magnus-the-collectioner commented
Если есть какие-то предложения, что конкретно можно попробовать расписать чуть подробнее - напишите, попробую это сделать на днях.

2021-09-12 08:49 UTC, SemyonSinchenko commented
> Если есть какие-то предложения, что конкретно можно попробовать расписать чуть подробнее - напишите, попробую это сделать на днях.

Я там в основном все сделал как коммит-саджешн, ты можешь просто тыкнуть в интерфейсе прямо (коммит саджешн). Вопрос ток по картинкам - скинь мне на них ссылки, я попробую поискать в качестве получше и надо ссылки на них ставить.

2021-09-12 10:39 UTC, Randl commented on qmlcourseRU/book/qnnblock/qnn.md
> +Схема обучения гибридной нейронной сети
на архиве можно скачать сорсы и там будут оригинальные картинки в том числе

2021-09-12 10:39 UTC, Randl commented on qmlcourseRU/book/qnnblock/qnn.md
> +Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как __ansatz__  -- по своей сути это заранее подготовленные участки параметрической схемы, которые
Возможно где-то (не факт что тут) стоит объяснить в целом что такое анзац -- https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D0%B7%D0%B0%D1%86

2021-09-12 10:39 UTC, Randl commented on qmlcourseRU/book/qnnblock/qnn.md
> + -- Трансформировать данные из классических в квантовые операторы;
операторы или все таки состояния?

2021-09-12 16:09 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Ansatz, соответствующий свёрточному слою нейронной сети в PennyLane
Поменял картинку, добавил ссылку.

2021-09-12 16:09 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Схема обучения гибридной нейронной сети
Поменял картинку, добавил ссылку.

2021-09-21 13:40 UTC, vtrokhymenko commented
@magnus-the-collectioner не забудь пж закончить лекцию

2021-11-10 06:15 UTC, vtrokhymenko commented
доступ к stage лекции – http://54.89.156.216/152_merge/_build/html/book/qnnblock/qnn.html

2021-11-15 23:30 UTC, meandmytram commented
Посмотрел лекцию, в качестве обзора очень круто получилось, как мне кажется. Подправил пару стилистических деталей.

2021-11-17 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +[Источник картинки](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.CVNeuralNetLayers.html)
вот что получаю, когда перехожу по сылке
```
SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.
]]]

2021-11-17 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Функция потерь работает таким же образом, как и в полностью классических сетях, так как оптимизация происходит на классическом железе -- единственное, что отличается, -- это объединение квантовых и к
```suggestion
Функция потерь работает таким же образом, как и в полностью классических сетях, так как оптимизация происходит на классическом железе -- единственное, что отличается, -- это объединение квантовых и классических градиентов. Градиент по нашей квантовой схеме получается при помощи замера состояния, которое может варьироваться из-за вероятностной природы кубита, поэтому несколько замеров позволяют аппроксимировать ожидаемый градиент при помощи методов вроде [finite differences](gradients) или [parameter shift](hogradients), после чего остаётся только совместить его с классическим.
```

2021-11-17 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +В этой лекции мы пройдёмся по расширению идеи нейронных сетей на квантовые компьютеры -- мы уже прошли и вариационные квантовые схемы (**VQC**), и комбинацию квантовых и классических градиентов в них
не добавить ли сюда ссылки на упомянутые лекции?

2021-11-17 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +- Оценить ошибку, рассчитать градиенты и обновить параметры.
```suggestion
- трансформировать данные из классических в квантовые представления;
- отправить эти данные для вычисления на квантовой схеме;
- просэмплировать и замерить результат квантовой схемы;
- отправить результаты для вычисления на классической схеме;
- оценить ошибку, рассчитать градиенты и обновить параметры.
```

2021-11-17 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как **ansatz** -- по своей сути это заранее подготовленные участки параметрической схемы, которые
> Более подробно мы остановимся на них слегка позже

можете ткнуть носом где именно об этом дальше упоминается?

2021-11-17 16:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Функция потерь работает таким же образом, как и в полностью классических сетях, так как оптимизация происходит на классическом железе -- единственное, что отличается, -- это объединение квантовых и к
и «parameter shift» как вообще правильно писать: с или без `-`, а то у нас по-разному это пишется?

2021-11-18 20:58 UTC, vtrokhymenko commented
@magnus-the-collectioner посмотришь мои комментарии, а то ты автор и вольный принимать решения что с ними делать?
и у других нет замечаний/предложений, а то охота уже влить в master?

2021-11-18 21:31 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как **ansatz** -- по своей сути это заранее подготовленные участки параметрической схемы, которые
Вроде там должна была быть следующая глава в самом курсе про анзацы, нет? Я поэтому на них не так заостряю внимание.

2021-11-18 21:32 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +В этой лекции мы пройдёмся по расширению идеи нейронных сетей на квантовые компьютеры -- мы уже прошли и вариационные квантовые схемы (**VQC**), и комбинацию квантовых и классических градиентов в них
Да, нужно, но я не знаю, как у нас структурно сейчас всё выглядит в мастере - добавишь ссылки на VQC и квантовые градиенты?

2021-11-18 21:33 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +Функция потерь работает таким же образом, как и в полностью классических сетях, так как оптимизация происходит на классическом железе -- единственное, что отличается, -- это объединение квантовых и к
Xanadu пишут через дефис, Qiskit пишут через пробел. Не суть важно, но возможно стоит консистентно с остальными лекциями.

2021-11-18 21:35 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +[Источник картинки](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.templates.layers.CVNeuralNetLayers.html)
Они переделали доку, теперь все слои здесь: https://pennylane.readthedocs.io/en/ising/code/templates/layers.html

2021-11-19 06:11 UTC, vtrokhymenko commented on qmlcourseRU/book/qnnblock/qnn.md
> +Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как **ansatz** -- по своей сути это заранее подготовленные участки параметрической схемы, которые
то есть ты писал о курсе, думал что речь о текущей лекции. ближайшее упоминание о анзаце планируется быть вот тут https://github.com/SemyonSinchenko/qmlcourse/pull/257/files

2021-11-19 07:39 UTC, magnus-the-collectioner commented on qmlcourseRU/book/qnnblock/qnn.md
> +Зачастую в литературе по **VQC**, особенно когда речь идёт о нейронных сетях, упоминается такая вещь как **ansatz** -- по своей сути это заранее подготовленные участки параметрической схемы, которые
Я думаю это окей, главное что оно есть дальше.

2021-11-19 17:28 UTC, vtrokhymenko commented
готов вливать в master, все всё просмотрели?

2021-11-19 18:08 UTC, SemyonSinchenko approved these changes

2021-11-19 19:01 UTC, merged

2021-11-19 19:01 UTC, vtrokhymenko commented
@magnus-the-collectioner спасибо за лекцию