[WIP] lecture/Simon algorithm
SemyonSinchenko/qmlcourse pull request #213
Opened 2021-10-21 14:48 UTC by polyzer

Ещё разок, чтобы книжка собиралась. Пока что ревью не требуется)

2021-11-01 10:46 UTC, vtrokhymenko commented
@polyzer отметьте пж какие с выше вопросов были решени

2021-11-01 10:50 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +[Qiskit Simon algorithm](https://qiskit.org/textbook/ch-algorithms/simon.html)
Если сделать без пробелов, то будет ссылки будут в одну линию... Как-то это криво)

2021-11-01 10:51 UTC, polyzer commented
@vtrokhymenko готово)

2021-11-01 11:04 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +[Qiskit Simon algorithm](https://qiskit.org/textbook/ch-algorithms/simon.html)
Так тут предлагается список (каждая строка с "-"), если я что понял

2021-11-01 11:11 UTC, Randl commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +          p_z = \left\| \frac{1}{2^n} \sum_{z \in \{0, 1\}^n} \left( ((-1)^{\langle z, x_1\rangle} + (-1)^{\langle z, x_2\rangle}) |\ell\rangle \right) \right\|^2 = \frac{1}{2^n}
Может \sum_{l \in A}? Иначе правая часть не зависит от z

2021-11-01 11:13 UTC, Randl commented
Имхо были помечены как resolved замечания на которые я ответа не получил и исправлений в тексте не заметил. Пометил назад, но это как-то странно

2021-11-01 11:14 UTC, Randl commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +        Перепишем коэффициенты $\langle (x_1 \oplus s, z \rangle = \langle (x_1, z \rangle \oplus \langle (x_2, z \rangle$:
Какие-то лишние скобки кажется

2021-11-01 11:15 UTC, Randl commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +        Сейчас разберёмся со случаем, когда $\langle z, s \rangle = 1$, $(-1)^{\langle z, s \rangle} = -1$
```suggestion
        Если $\langle z, s \rangle = 1$, то $(-1)^{\langle z, s \rangle} = -1$ и следовательно
```

2021-11-01 11:15 UTC, Randl commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +        Сейчас разберёмся со случаем, когда $\langle z, s \rangle = 0$, $(-1)^{\langle z, s \rangle} = 1$
```suggestion
       Иначе $\langle z, s \rangle = 0$, и тогда $(-1)^{\langle z, s \rangle} = 1$:
```

2021-11-01 11:16 UTC, Randl commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +          (-1)^{\langle x_1, z \rangle} (1 + (-1)^{\langle z, s \rangle}) = (-1)^{\langle x_1, z \rangle} 2
лишняя двойка?

2021-11-01 16:31 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +          (-1)^{\langle x_1, z \rangle} (1 + (-1)^{\langle z, s \rangle}) = (-1)^{\langle x_1, z \rangle} 2
2 \cdot (-1)^{\langle x_1, z \rangle} - оно

2021-11-03 07:27 UTC, Randl commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +          (-1)^{\langle x_1, z \rangle} (1 + (-1)^{\langle z, s \rangle}) = (-1)^{\langle x_1, z \rangle} 2
Лучше двойку в начало перенести наверное тогда

2021-11-03 20:28 UTC, vtrokhymenko commented on qmlcourseRU/_toc.yml
> +      title: 🟧 Алгоритм Саймона
как-то странно что рыжий квадрат не отрисовывается
![image](https://user-images.githubusercontent.com/8581044/140187626-6d11390a-abb8-4285-aa8f-c1baf421662d.png)

2021-11-04 00:01 UTC, SemyonSinchenko requested changes

2021-11-04 00:01 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +# Приложение
В каждй лекции может должен быть один и только один заголовок уровня #. Иначе игнорится тот заголовок, который указан в _toc. Сейчас именно из-за этого лекция не отображается цветом.

2021-11-04 00:02 UTC, SemyonSinchenko commented on qmlcourseRU/_toc.yml
> +      title: 🟧 Алгоритм Саймона
Там в тексте два заголовка уровня #, из-за этого книга ломается

2021-11-04 10:38 UTC, vtrokhymenko commented
залил master, дабы обновить немного эту лекцию, надеюсь ничего не потерялось и летнего не добавилось

2021-11-04 10:57 UTC, vtrokhymenko commented
что-то master не весь влился, хотя ci по deploy в aws сработал, но ветка с номером не появилась

2021-11-04 12:31 UTC, SemyonSinchenko approved these changes

2021-11-04 13:35 UTC, vtrokhymenko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +        Перепишем коэффициенты $\langle (x_1 \oplus s, z \rangle = \langle (x_1, z \rangle \oplus \langle (x_2, z \rangle$:
вроде все норм в последнем [варианте](http://54.89.156.216/213_merge/_build/html/book/qcalgo/simon_algorithm.html)

2021-11-04 13:38 UTC, vtrokhymenko commented
@polyzer посмотри пж выше открытые вопросы/замечания и доделай если есть. после будем уже лить в master

2021-11-04 17:39 UTC, polyzer commented
@vtrokhymenko ок, гляну

2021-11-05 12:30 UTC, Yorko requested changes
В математику не лез. Пофиксил запятые и прочие мелочи, оставил коменты.

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +  \langle x, z\rangle = \bigoplus_{i=0}^{2^n-1} x_i \wedge z_i
Стоит пояснить, что такое $\bigoplus$

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +2. Применяем матрицы Адамара на первом регистре:
> матрицы Адамара 

Лучше "гейты Адамара", мы их всюду гейтами кличем

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +3. Применяем оператор $U_f$:
Да, это ж ключевой момент, надо аккуратно определить

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +      |\psi \rangle_3 = \frac{1}{\sqrt{2}} \left( |x\rangle_1 + |y\rangle_1\rangle \right)
Тут что-то не так с индексами "1"

<img src="https://habrastorage.org/webt/y0/fu/ob/y0fuobb93uwofn_xuvdjfku1n5w.png" />

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +        т.е. имеем вероятность получить строку $z$ на первом регистре
сложно предложение читается, может, разбить?

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +    Расчёты вероятностей можно найти в приложениях (Приложение 1).
Кросс-реф ссылку вот так можно сделать: \[Приложение 1\](simon_algorithm.html#id6)

2021-11-05 12:30 UTC, Yorko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +Нарисуем схему на Qiskit, которая будет показывать одну итерацию алгоритма:
А долго на `PennyLane` переделать? Мы всюду в курсе `PennyLane` юзаем

2021-11-05 13:50 UTC, vtrokhymenko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +    Расчёты вероятностей можно найти в приложениях (Приложение 1).
только не html, а md видимо

2021-11-05 13:51 UTC, vtrokhymenko commented on qmlcourseRU/_toc.yml
> +      title: 🟩 Классический SVM
а зачем тут svm-то?

2021-11-05 18:32 UTC, alexey-pronkin commented on qmlcourseRU/book/authors.md
>  7. [Юрий Кашницкий](https://github.com/alexey-pronkin)
ссылку сломали у Юрия.

2021-11-05 18:38 UTC, alexey-pronkin commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +Нарисуем схему на Qiskit, которая будет показывать одну итерацию алгоритма:
Не всюду вроде, qiskit тоже стоит в окружении

2021-11-05 20:17 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +Нарисуем схему на Qiskit, которая будет показывать одну итерацию алгоритма:
@Yorko Попробую на PL, раз нужно.
@alexey-pronkin из-за меня и ставили, похоже. Я уже в одной из лекций Qiskit притаскивал.

2021-11-06 10:57 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +    Расчёты вероятностей можно найти в приложениях (Приложение 1).
html, т.к. собирается в html же.

2021-11-06 11:24 UTC, SemyonSinchenko commented
Давайте доведем до какого-то финального статуса и смержим. А то в пн она уже открывается.

2021-11-06 12:31 UTC, SemyonSinchenko commented on qmlcourseRU/_toc.yml
> +      title: 🟩 Классический SVM
@Yorko втащил, 100%

2021-11-06 13:33 UTC, vtrokhymenko commented
> Давайте доведем до какого-то финального статуса и смержим. А то в пн она уже открывается.

есть определенны не закрытые моменты, судя по истории выше, а так да, уже пора

2021-11-06 13:47 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +        т.е. имеем вероятность получить строку $z$ на первом регистре
Немножко подредактил. Нужна конкретная идея по разбиению, если что-то непонятно

2021-11-06 13:48 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +  $$\large f(x) = f(y) \Leftrightarrow x \oplus y = s$$
Там теперь дано определение, вроде.

2021-11-06 13:48 UTC, polyzer commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +3. Применяем оператор $U_f$:
Вроде написал.

2021-11-07 15:38 UTC, SemyonSinchenko approved these changes

2021-11-07 19:18 UTC, merged

2021-11-07 19:18 UTC, SemyonSinchenko commented
Все, больше ждать нельзя. Будет как будет.

2021-11-07 19:25 UTC, vtrokhymenko commented
но доделывать лекцию никто не мешает; если кто хочет, делайте в новой ветке