Ising model
SemyonSinchenko/qmlcourse pull request #228
Opened 2021-10-25 14:26 UTC by SemyonSinchenko

Автор лекции (Дмитрий Бажанов) еще только разбирается в работе с GitHub. Он будет видеть комментарии, но изменения буду вносить пока я.

Это лекции по Изингу: общая и продвинутая.

On branch lecture/ising
Changes to be committed:
- modified:   qmlcourseRU/_bibliography/references.bib
- new file:   qmlcourseRU/_static/problemsblock/ising/Max-cut.png
- new file:   qmlcourseRU/_static/problemsblock/ising/af_ordering.png
- modified:   qmlcourseRU/_toc.yml
- modified:   qmlcourseRU/book/authors.md
- new file:   qmlcourseRU/book/problemsblock/advising.md
- new file:   qmlcourseRU/book/problemsblock/ising.md

Базовая: https://semyonsinchenko.github.io/qmlcourse/_build/html/book/problemsblock/ising.html
Продвинутая: https://semyonsinchenko.github.io/qmlcourse/_build/html/book/problemsblock/advising.html

close #208

2021-11-05 15:43 UTC, Yorko requested changes
Пока поревьюил первую часть - в целом понятно, некоторые замечания есть. Вторую часть вряд ли осилю.

2021-11-05 15:43 UTC, Yorko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h\neq 0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1} - h\sum_{i=0}^N \sigma^{z}_i
Если H -- со значком оператора, то по-хорошему надо и у Паули ставить знак оператора

2021-11-05 15:43 UTC, Yorko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h=0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1}
не факт, что принципиально, но в курсе QML на edX говорят, тут минус должен быть перед $J$

2021-11-05 15:43 UTC, Yorko commented on qmlcourseRU/book/problemsblock/ising.md
> +Давайте теперь запишем Гамильтониан такой системы. Для представления магнитных моментов мы будем использовать оператор $\sigma^z$ -- другими словами, спин в
Стоит пояснить, что такое Гамильтониан и почему природа пытается его минимизировать

2021-11-05 15:43 UTC, Yorko commented on qmlcourseRU/book/problemsblock/ising.md
> +Давайте теперь запишем Гамильтониан такой системы. Для представления магнитных моментов мы будем использовать оператор $\sigma^z$ -- другими словами, спин в
вижу комментарий далее. Может, стоит его сюда перенести, пораньше чтоб был. И пояснить про гамильтониан

2021-11-05 15:43 UTC, Yorko commented on qmlcourseRU/book/problemsblock/ising.md
> +Тут мы порльзуемся рутинами из `ARPACK`, подробнее о которых можно почитать во вводных лекциях по линейной алгебре.
ARPACk мы не покрываем во вводном блоке

2021-11-05 16:35 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h=0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1}
Значит у них ферромагнитная модель. А у нас антиферромагнитная.

2021-11-05 16:36 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +Тут мы порльзуемся рутинами из `ARPACK`, подробнее о которых можно почитать во вводных лекциях по линейной алгебре.
Да, я поправлю... А так хотелось покрыть. Сейчас там даже разреденных матриц нет(

2021-11-05 18:23 UTC, alexey-pronkin commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h\neq 0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1} - h\sum_{i=0}^N \sigma^{z}_i
Вообще, кстати, не понятно, зачем вы шляпы ставите, обычно так отделяют какой-то определенный вид матриц/операторов, а у нас тут все унитарно.

2021-11-05 18:25 UTC, alexey-pronkin commented on qmlcourseRU/book/problemsblock/ising.md
> +Тут мы порльзуемся рутинами из `ARPACK`, подробнее о которых можно почитать во вводных лекциях по линейной алгебре.
Это же не курс по вычислительной линейной алгебре, для такого нужен отдельный курс. Воспользоваться чем-то blackbox в библиотеке это норм.

2021-11-05 19:43 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h\neq 0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1} - h\sum_{i=0}^N \sigma^{z}_i
Обычно для H шляпу ставят всегда, а вот на сигмы паули часто забивают. Я за то, чтобы шляпы везде.

2021-11-06 08:58 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +Давайте теперь запишем Гамильтониан такой системы. Для представления магнитных моментов мы будем использовать оператор $\sigma^z$ -- другими словами, спин в
Добавил

2021-11-06 08:58 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +Тут мы порльзуемся рутинами из `ARPACK`, подробнее о которых можно почитать во вводных лекциях по линейной алгебре.
Вставил ссылку на доку

2021-11-06 08:59 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h\neq 0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1} - h\sum_{i=0}^N \sigma^{z}_i
Добавил шляпы

2021-11-06 11:04 UTC, vtrokhymenko commented on qmlcourseRU/book/problemsblock/advising.md
> +При этом величина статистической суммы  не меняется, поскольку след матрицы является ее инвариантом. Отметим, что процедуру диагонализации трансфер-матрицы можно провести множеством способов. В завис
```suggestion
При этом величина статистической суммы  не меняется, поскольку след матрицы является ее инвариантом. Отметим, что процедуру диагонализации трансфер-матрицы можно провести множеством способов. В зависимости от подбора диагонализирующей матрицы $U$ её можно провести таким образом, что на первом месте в матрице $\grave{T}$ будет стоять её главное (единственное максимальное вещественное) собственное значение, которое всегда существует по теореме Фробениуса–Перрона. Если на первое место в спектре трансфер-матрицы поставить ее главное собственное значение, то статистическую сумму {eq}`eqn:10` можно переписать как:
```

2021-11-07 07:43 UTC, Randl commented on qmlcourseRU/book/problemsblock/advising.md
> +E(\{\sigma\}) = -J\sum_{i=1}^N \sigma_i \sigma_{i+1} - H\sum_{i=1}^N \sigma_i.
стоит обозначения унифицировать, в прошлой лекции H для гамильтониана и h для поля (стандартная нотация вроде)

2021-11-07 07:43 UTC, Randl commented on qmlcourseRU/book/problemsblock/advising.md
> +Для описания такой системы необходимо найти статистическую сумму $Z$ , в которой содержится полная информация о всех состояниях системы. Тогда другие характеристики системы, такие как удельная энерги
> Для описания такой системы 

Возникает ощушение что статсумма это что-то специфичное то ли для переодических ГУ то ли для Изинга, в то время как это очень общая концепция

2021-11-07 07:43 UTC, Randl commented on qmlcourseRU/book/problemsblock/advising.md
> +T_{\sigma \sigma'} = <\sigma|T|\sigma'> = e^{t\sigma\sigma' +\frac{h}{2}(\sigma + \sigma')},
```suggestion
T_{\sigma \sigma'} = \langle \sigma|T|\sigma' \rangle = e^{t\sigma\sigma' +\frac{h}{2}(\sigma + \sigma')},
```

2021-11-07 07:43 UTC, Randl commented on qmlcourseRU/book/problemsblock/advising.md
> +T = \begin{vmatrix}
pmatrix?

2021-11-07 07:43 UTC, Randl commented on qmlcourseRU/book/problemsblock/advising.md
> +\grave{T} = U^{-1}TU = dgn\{\lambda_1, \lambda_2, . . . , \lambda_r\},
мб \tilde или что-то такое а то странно выглядит

2021-11-07 07:43 UTC, Randl commented on qmlcourseRU/book/problemsblock/advising.md
> +где $ch (h) = \frac{e^{h} + e^{-h}}{2}$ - гиперболический косинус и $sh (h) = \frac{e^{h} - e^{-h}}{2}$ - гиперболический синус. Следовательно статистическая сумма рассматриваемой модели записывается
\cosh и \sinh ?

2021-11-07 22:39 UTC, Yorko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h=0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1}
Не, у них тоже антиферромагнитная. И минус перед J. [В вики тоже минус](https://en.wikipedia.org/wiki/Ising_model), а дальше уже от знака J зависит:

- J_{ij} > 0, the interaction is called ferromagnetic,
- J_{ij} < 0 the interaction is called antiferromagnetic,
- J_{ij} = 0, the spins are noninteracting.

2021-11-07 22:44 UTC, Yorko requested changes
Надо бы разобраться со знаками перед J в гамильтониане

2021-11-08 03:34 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/ising.md
> +\hat{H}_{h=0} = J \sum_{i=0}^{N-1} \sigma^{z}_i\sigma^{z}_{i+1}
Дело вкуса. Но ок, давай поставим минус.

2021-11-08 07:09 UTC, Randl commented
Знак перед J не оч важен, вроде минус стандартнее

2021-11-08 09:47 UTC, merged

2021-11-08 09:49 UTC, SemyonSinchenko commented
@vtrokhymenko Ты что-то дерзко смержил... Я тут думал еще пару правок внести по комментам. Но ок, сделаю через Issue.

2021-11-08 10:50 UTC, vtrokhymenko commented
специально не удаляю ветку, куда можете делать commits для #264 и опосля дольем