qaoa
SemyonSinchenko/qmlcourse pull request #257
Opened 2021-11-01 17:52 UTC by vtrokhymenko

я тут вы ступаю как секретера, в лекции болван. пока ещё не смотрел как выглядит, тк проблемы со сборкой, но вы уже начинайте смотреть

автор сией лекции @Carinetta (будет здорово, если зайдете и добавить/замените что нужно, можете хоть текстом)

вот сама лекций
[Carina_QAOA_QAOAz.docx](https://github.com/SemyonSinchenko/qmlcourse/files/7455193/Carina_QAOA_QAOAz.docx)

2021-11-01 18:38 UTC, polyzer commented
Совсем сыро и мало... QAOA считаю слишком важной темой для курса (как и VQE), надо во всех подробностях описывать.
Тем, кто будет делать лекцию рекомендую вот эти статьи: 
[A Quantum Approximate Optimization Algorithm](https://arxiv.org/abs/1411.4028) (оригинальная)
и ещё хорошая [From the Quantum Approximate Optimization Algorithm to a Quantum Alternating Operator Ansatz](https://arxiv.org/abs/1709.03489)

2021-11-01 23:27 UTC, meandmytram commented
Всем привет. Я посмотрел то, что есть в лекции на данный момент, и мне кажется тут еще очень много работы. У меня одного сейчас нет времени этим заниматься, но я готов кому-то помочь, если нужно.

2021-11-02 06:48 UTC, Carinetta commented
Ребят, выручайте кто во что умеет, у меня временно жизни кончились.
Это, можно считать, рыба лекции. Мне понравилась концепция кискита: https://qiskit.org/textbook/ch-applications/qaoa.html - её и прикинула. Но они тоже особо не церемонятся в подробностях

2021-11-03 21:32 UTC, alexey-pronkin commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Алгоритм квантовой приближенной оптимизации (`Quantum Approximate Optimization Algorithm (QAOA)`) -- алгоритм поиска оптимального решения для комбинаторных задач оптимизации. В частности, алгоритм мо
больгим -> большим

2021-11-14 13:48 UTC, vtrokhymenko commented
@meandmytram нет желания закончить сию лекцию, сильно выручишь? а то в таком виде, к сожалению, не сможем её выпустить, а хотелось бы, негоже терять такие знания

2021-11-14 23:25 UTC, meandmytram commented
@vtrokhymenko до декабря асболютный завал, сорри

2021-11-25 00:39 UTC, meandmytram commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Анзац является расширением классического `QAOA`, использующий преимущества унитариев, а не только эволюции гамильтониана во времени. Он позволяет более эффективно реализовывать операции смешивания, о
Не понял это предложение

2021-11-25 00:39 UTC, meandmytram commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Анзац является расширением классического `QAOA`, использующий преимущества унитариев, а не только эволюции гамильтониана во времени. Он позволяет более эффективно реализовывать операции смешивания, о
(первую фразу на 133 строке)

2021-11-25 06:20 UTC, Carinetta commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Анзац является расширением классического `QAOA`, использующий преимущества унитариев, а не только эволюции гамильтониана во времени. Он позволяет более эффективно реализовывать операции смешивания, о
@meandmytram, вот тоже сомневаюсь.
Может, просто выпилить это предложение?
+- подобные формулировки мелькают в источниках - и игнорить рука не поднялась, и расшатать семантику не удалось. В переводе тоже немного степеней свободы.
Давай уберём всё, что вызывает многосмыслие.

2021-11-27 12:00 UTC, Carinetta commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Анзац является расширением классического `QAOA`, использующий преимущества унитариев, а не только эволюции гамильтониана во времени. Он позволяет более эффективно реализовывать операции смешивания, о
Из оригиналочки "..the quantum alternating operator ansatz, is the consideration of general parameterized families of **_unitaries_** rather than only those corresponding to the time evolution under a fixed local Hamiltonian..."

@vtrokhymenko, я думаю, по всем замечаниям Александра @meandmytram скользкие места лучше пока просто удалить.

2021-11-27 12:04 UTC, Randl commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Анзац является расширением классического `QAOA`, использующий преимущества унитариев, а не только эволюции гамильтониана во времени. Он позволяет более эффективно реализовывать операции смешивания, о
Анзац рассматривает более общие параметризированные унитарные трансформации, а не только соответствующие эволюции фиксированного локального Гамильтониана во времени

2021-11-29 15:39 UTC, vtrokhymenko commented
у меня всё, проверяйте

2021-11-30 07:28 UTC, SemyonSinchenko commented
Мне не нравится, что в лекции идет сразу "заход с козырей": мы начинаем с хардовых формул, как будто это справочник Кнута, где просто описан алгоритм, а не лекция, которая, как мне кажется, должна давать интуицию. Даже о задаче почти ни слова, ну и совершенно не ясно "а почему мы делаем именно так и что вообще происходит?"

Может стоит в начале попробовать "на пальцах" объяснить, как вообще появляется QAOA? Просто я всегда его понимал так, что у нас есть гамильтонианное представление задачи (про это у нас аж две лекции) - мы формулируем нашу оптимизацию, как модель Изинга. А дальше мы знаем, что физическая система в реальном мире должна релаксировать сама собой в свое основное состояние, то есть если бы мы могли "построить" такую систему, которая соответствует этой задаче в вакууме и подождать достаточно долго, то мы бы автоматом получили решение. Ну а дальше главный трюк - строить нам не хочется, поэтому давайте попробуем "просимулировать" квантовую динамику - это делается при помощи Suzuki-Trotter (материала в инете море, например: https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/chemistry/concepts/algorithms, или https://web.northeastern.edu/afeiguin/phys5870/phys5870/node103.html? ну или море их разных). И если сильно-сильно упростить, то мне кажется можно вполне сказать, что мы просто берем наше уравнение Шредингера (которое описывает квантовую динамику) и засовываем в формулы Suzuki-Trotter. И именно так у нас получается последовательное и многократное применение cost и mixed гамильтонианов! Ну а дальше уже переходить к самому QAOA. Понятно, что не надо тут расписывать само разложение S-T, досаточно просто дать финальную формулу или написать словами. Можно и уравнение Шредингера даже не писать полностью, но какая-то интуиция, кмк, должна быть. По крайней мере я для себя всегда понимал QAOA именно так...

@vtrokhymenko @Carinetta @meandmytram @Randl или я фигню какую-то несу и это всех только запутает?

2021-11-30 08:05 UTC, SemyonSinchenko commented
Из мелочей:

- [ ] Добавить цитирование работы про QAOA (https://arxiv.org/abs/1411.4028)
- [ ] Добавить цитирования на работы про анзацы (оно гуглится)
- [ ] Привести примеры "задач оптимизации n-разрядного набора данных" - у нас целый блок про то, какие гамильтонианы можно оптимизировать
- [ ] Добавить реальный пример (можно используя верхнеуровневые API, но идеально написать самому). Пример: https://pennylane.ai/qml/demos/tutorial_qaoa_maxcut.html (низкоуровневый API) или https://pennylane.ai/qml/demos/tutorial_qaoa_intro.html#minimum-vertex-cover-with-qaoa (высокоуровневый API)

2021-11-30 14:50 UTC, Carinetta commented
@SemyonSinchenko 
Замечания хорошие, о многих сама думала.
1. Лекция писалась давно, изначально для других целей. И именно так, как самой хотелось бы читать. Это оч индивидуально: мне, например, понятнее, когда с разбегу - в корень-схемы-формулы. Кому-то нужнее обвязки "откуда-для чего".
2. Несколько раз честно садилась допилить вступление и примеры - ничего красивого не выходит, всё возвращается к истоку.
3. Где-то уже жаловалась, что под конец года на работе адский бдсм: релизим машины для очень, сильно первых лиц чуть ли не по 12 часов в сутки + учёба. Там, где появляется время, не хватает мозгов. Вот этот ответ для меня как перекур на свежем воздухе.

За любые предложенные дополнения - обеими руками и с кружками - если кто-то умеет и может внести. В ближайшие месяц-два не вывезу - старалась.

2021-12-08 10:33 UTC, SemyonSinchenko commented
@vtrokhymenko @Carinetta Написал введение, посмотрите.

2021-12-08 10:56 UTC, SemyonSinchenko approved these changes

2021-12-08 11:45 UTC, Yorko requested changes

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +И в лекции о `D-Wave` указывалось на главную проблему -- риск перехода системы из основного состояния в возбужденное при недостаточно медленном изменении параметров $A$ и $B$:
```suggestion
В той же [лекции](swave) о `D-Wave` указывалась главая проблема -- риск перехода системы из основного состояния в возбужденное при недостаточно медленном изменении параметров $A$ и $B$:
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +В прошлых лекция активно [рассказывалось](dwave) о квантовых аннилерах -- аналоговых устройствах, реализующих поиск основного состояния системы. Выпишем еще раз [гамильтониан](../dwaveblock/dwave.htm
> аннилерах

Мы их раньше отжигателями называли

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +В данном случае наша цель получить выражение для финального состояния $\Psi$, которое будет отвечать решению квантового аннилера. Финальное состояние есть решение уравнения Шредингера:
```suggestion
В данном случае наша цель -- получить выражение для финального состояния $\ket{\Psi}$, которое будет отвечать решению квантового отжигателя. Финальное состояние есть решение уравнения Шредингера:
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Для решение проблемы "нерешаемости" уравнение Шредингера перейдем от непрерывного времени $t$ и зависимостей $A(t)$ и $B(t)$ к $N$ дискретных моментов времени $t_1, t2_2, ..., t_n$. Тогда можно замен
```suggestion
Для решение проблемы "нерешаемости" уравнения Шредингера перейдем от непрерывного времени $t$ и зависимостей $A(t)$ и $B(t)$ к $N$ дискретных моментов времени $t_1, t_2, ..., t_n$. Тогда можно заменить расписание отжига в виде непрерывных коэффициентов на набор дискретных коэффициентов, каждый из которых отвечает своему моменту времени:
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +А это уже хорошо знакомая задача оптимизации результата измерения состояния, заданного при помощи некоторой [**VQC**](vqc), которая параметризированая набором действительных чисел $\gamma_1, ..., \ga
```suggestion
А это уже хорошо знакомая задача оптимизации результата измерения состояния, заданного при помощи некоторой [**VQC**](vqc), которая параметризированая набором действительных чисел $\gamma_1, ..., \gamma_N, \beta_1, ..., \beta_N$. И эта задача решается хорошо уже знакомыми [градиентными методами](gradients).
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Итак, алгоритм состоит со следующих основных этапов:
```suggestion
Итак, алгоритм состоит из следующих основных этапов:
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +    например вот так
```suggestion
    например, вот так
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +    H_p = (I_0 \otimes Z_1 \otimes I_2 \otimes Z_3)
Тут $H_p$ должно быть или $U_{\text{phase}}$ ?

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +    Z = \begin{bmatrix} 0 & 1 \\ 1 & 0\end{bmatrix}
```suggestion
    X = \begin{bmatrix} 0 & 1 \\ 1 & 0\end{bmatrix}
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +В данном алгоритме используется адиабатический метод эволюции состояния $\ket{\Psi_0}$ с переменным гамильтонианом: на каждой итерации параметры $\beta$ и $\gamma$ понемногу изменяются.
Нужна ссылка на адиабатический метод. Например,

Edward Farhi, Jeffrey Goldstone, Sam Gutmann, Michael Sipser.
Quantum computation by adiabatic evolution, 2000.
arXiv:quant-ph/0001106.

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Применение "анзаца" в алгоритме квантовой приближенной оптимизации заключается в модернизации оператора смешивания $U_{mix}$ и предполагает использование $CNOT$, а не $X$.
```suggestion
Применение "анзаца" в алгоритме квантовой приближенной оптимизации заключается в модернизации оператора смешивания $U_{mixer}$ и предполагает использование $CNOT$, а не $X$.
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Применение "анзаца" в алгоритме квантовой приближенной оптимизации заключается в модернизации оператора смешивания $U_{mix}$ и предполагает использование $CNOT$, а не $X$.
Тут бы ссылку на анзацы

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Анзац рассматривает более общие параметризированные унитарные трансформации, а не только соответствующие эволюции фиксированного локального Гамильтониана во времени. Он позволяет более эффективно реа
```suggestion
Анзац рассматривает более общие параметризированные унитарные трансформации, а не только соответствующие эволюции фиксированного локального гамильтониана во времени. Он позволяет более эффективно реализовывать операции смешивания, особенно в задачах оптимизации с жесткими ограничениями.
```

2021-12-08 11:45 UTC, Yorko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Конечно, к компоновке миксованных гейтов можно подходить сколь угодно творчески, и пример общей схемы, реализующий QAOAz, представлен ниже:
```suggestion
Конечно, к компоновке смешанных гейтов можно подходить сколь угодно творчески, и пример общей схемы, реализующей QAOAz, представлен ниже:
```

2021-12-08 15:52 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +:name: fig_2
```suggestion
В той же [лекции](swave) о `D-Wave` указывалась главая проблема -- риск перехода системы из основного состояния в возбужденное при недостаточно медленном изменении параметров $A$ и $B$:

```{figure} /_static/dwaveblock/dwave/fig_1.png
:name: fig_2
```

2021-12-08 15:52 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +У отжига "в железе" есть существенная проблема -- нам трудно правильным образом подбирать расписание отжига. Но есть и другая идея! Изначально квантовые компьютеры создавались для симуляции квантовой
```suggestion
У отжига "в железе" есть существенная проблема -- трудно правильным образом подбирать расписание отжига. Но есть и другая идея! Изначально квантовые компьютеры создавались для симуляции квантовой динамики. Воспользуемся техникой симуляции, которая называется _trotterization_.
```

2021-12-08 15:52 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +где $\mathcal{H}_{initial}$ -- это _tunneling_ или начальный гамильтониан, а $\mathcal{H}_{cost}$ -- это так называемый _problem_ или _cost_ гамильтониан, который отвечает задаче. Подробно эти темы о
```suggestion
$$
\ket{\Psi(t)} = e^{-i\mathcal{H}_{Ising}(t)t}\ket{\Psi(0)} = e^{-i(A(t) \mathcal{H}_{initial} + B(t)\mathcal{H}_{cost})t}\ket{\Psi(0)},
$$

где $\mathcal{H}_{initial}$ -- это _tunneling_ или начальный гамильтониан, а $\mathcal{H}_{cost}$ -- это так называемый _problem_ или _cost_ гамильтониан, который отвечает задаче. Подробно эти темы обсуждались в [лекции о D-Wave](dwave). Для тех, кто сейчас ничего не понял, рекомендуется также вернуться к лекции [о переходе от комбинаторных задач к гамильтонианам](np2ising), чтобы понять, как получается _cost_ гамильтониан.
```

2021-12-08 15:52 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +Рассмотрим задачу оптимизации $n$-разрядного набора данных, для которого мы стремимся найти некоторый минимум (или максимум). Алгоритм задается двумя гамильтонианами $H_{p}$ и $H_{M}$, а также $2p$ п
```suggestion
Рассмотрим задачу оптимизации $n$-разрядного набора данных, для которого нужно найти некоторый минимум (или максимум). Алгоритм задается двумя гамильтонианами $H_{p}$ и $H_{M}$, а также $2p$ параметрами: $\gamma_{1}, ..., \gamma_{p}$ и $\beta_{1}, ..., \beta_{p}$.
```

2021-12-08 15:52 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +
```suggestion
`QAOA` использует унитарный оператор $U(\beta,\gamma)$, принимающий на вход вещественные параметры $\beta$, $\gamma$, и описывается уже знакомым квантовым состоянием $\ket{\Psi}$. Цель поиска -- найти те самые оптимальные $\beta_{\text{opt}}$ и $\gamma_{\text{opt}}$.

```

2021-12-08 15:52 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +## Quantum Alternating Operator Ansatz
```suggestion
Возвращается лучшее решение, найденное за всё время поиска.

## Quantum Alternating Operator Ansatz
```

2021-12-10 01:30 UTC, Yorko approved these changes

2021-12-10 06:51 UTC, vtrokhymenko commented on qmlcourseRU/book/qaoablock/qaoa.md
> +    H_p = (I_0 \otimes Z_1 \otimes I_2 \otimes Z_3)
@SemyonSinchenko

2021-12-10 06:54 UTC, vtrokhymenko commented
теперь тут изменено 33 файл после того как влили master, как так-то?

2021-12-10 09:11 UTC, Yorko commented
> теперь тут изменено 33 файл после того как влили master, как так-то?

не знаю, почему он в диффе показывает лишние файлы – они уже и так в мастере. Поднял этот вопрос в слэке

2021-12-10 10:30 UTC, Yorko commented
Думал, это я рукожоп, но это "фича" гитхаба – [StackOverflow](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch), в диффе действительно показывались файлы из других PR, уже вмерженных в мастера. 

> Here's a good workaround. Use the `Edit` button when viewing the PR in GitHub to change the base branch to something other than `master`. Then switch it back to master and it will now correctly show only the changes from the most recent commits.

Это сработало.

2021-12-10 10:55 UTC, vtrokhymenko commented
предлагаю лить в master, вроде всё готово для этого

2021-12-10 10:57 UTC, SemyonSinchenko commented
> предлагаю лить в master, вроде всё готово для этого

@meandmytram @Carinetta Сможете посмотреть то, что я написал? Все ли мои "упрощения" корректны?

2021-12-10 12:49 UTC, Carinetta commented
Да, завтра или даже сегодня постараюсь вычитать

2021-12-10 16:14 UTC, Carinetta commented
мне нра - читается просто и приятно

56 строчка "Для решениЯ проблемы..."
78 "которая параметризированА_ набором"

2021-12-11 17:48 UTC, SemyonSinchenko commented
> 56 строчка "Для решениЯ проблемы..." 78 "которая параметризированА_ набором"

Готово.

2021-12-11 17:57 UTC, vtrokhymenko commented
> > 56 строчка "Для решениЯ проблемы..." 78 "которая параметризированА_ набором"
> 
> Готово.

pre-commit упали только

2021-12-11 19:10 UTC, merged