добавил авторов к лекциям
SemyonSinchenko/qmlcourse pull request #343
Opened 2021-12-15 11:26 UTC by vtrokhymenko

проверьте все внимательно правильно ли указал. есть пустые места, допишитесь сами или добавьте кто помнит делал какую лекцию

2021-12-15 11:37 UTC, SemyonSinchenko requested changes

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/problemsblock/advising.md
> +- [Синченко Семен](https://github.com/SemyonSinchenko)
```suggestion
- [Бажанов Дмитрий](https://github.com/dbazhanov)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/progblock/cirq_tfq.md
> +-
```suggestion
- [Синченко Семен](https://github.com/SemyonSinchenko)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/progblock/pennylane.md
> +-
```suggestion
- [Ширкин Сергей](https://github.com/SergeiShirkin)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/progblock/progreview.md
> +-
```suggestion
- [Синченко Семен](https://github.com/SemyonSinchenko)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/progblock/qiskit.md
> +-
```suggestion
- [Синченко Семен](https://github.com/SemyonSinchenko)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcalgo/deutschs_algorithm.md
> +-
```suggestion
- [Ширкин Сергей](https://github.com/SergeiShirkin)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcalgo/grovers_algorithm.md
> +-
```suggestion
- [Ширкин Сергей](https://github.com/SergeiShirkin)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcalgo/quantum_algorithms_overview.md
> +-
```suggestion
- [Ширкин Сергей](https://github.com/SergeiShirkin)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcalgo/simon_algorithm.md
> +- [Токарев Игорь](https://github.com/polyzer)
```suggestion
- [Решетова Карина](https://github.com/Carinetta)
- [Токарев Игорь](https://github.com/polyzer)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcblock/gates.md
> +-
```suggestion
- [Синченко Семен](https://github.com/SemyonSinchenko)
- [Беседин Илья](https://github.com/ooovector)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcblock/mixedstates.md
> +-
```suggestion
- [Карелин Николай](https://github.com/karelin)
- [Синченко Семен](https://github.com/SemyonSinchenko)
- [Беседин Илья](https://github.com/ooovector)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcblock/qubit.md
> +-
```suggestion
- [Синченко Семен](https://github.com/SemyonSinchenko)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qmlkindsblock/hhl_algorithm.md
> +-
```suggestion
- [Решетова Карина](https://github.com/Carinetta)
- [Токарев Игорь](https://github.com/polyzer)
```

2021-12-15 11:37 UTC, SemyonSinchenko commented on qmlcourseRU/book/qnnblock/qconv.md
> +-
```suggestion
- [Петров Вадим](https://github.com/belgraviton)
```

2021-12-15 12:01 UTC, alexey-pronkin requested changes

2021-12-15 12:01 UTC, alexey-pronkin commented on qmlcourseRU/book/linalgblock/bra-ket.md
> +- [Озерин Алексей](https://github.com/m12sl)
```suggestion
- [Озерин Алексей](https://github.com/m12sl)

```
Добавил Алексея, он изначально делал план лекции
И еще исправил опечатку, чтобы потом не мерджить разные ветки

2021-12-15 12:02 UTC, vtrokhymenko commented on qmlcourseRU/book/linalgblock/bra-ket.md
> +- [Озерин Алексей](https://github.com/m12sl)
ты решил и push и отзыв сделать? что то важнее у тебя тогда?

2021-12-15 12:07 UTC, alexey-pronkin commented on qmlcourseRU/book/linalgblock/bra-ket.md
> +- [Озерин Алексей](https://github.com/m12sl)
Я просто увидел, что забыл пустую строку поставить и решил в отзыве исправить заодно. А так я все посмотрел, что знаю с учетом комментариев Семена все остальное вроде верно (что я знаю).

2021-12-15 12:12 UTC, alexey-pronkin approved these changes

2021-12-15 13:35 UTC, vtrokhymenko commented
@alexey-pronkin что тут делает #339? этот pr о другом. давай делать правильно: на каждую задачу отдельный pr (тут не тот случай, когда задачи можно объединить)

2021-12-15 14:38 UTC, Yorko commented on qmlcourseRU/book/authors.md
> +- [Бажанов Дмитрий](https://github.com/dbazhanov)
Я бы сортировал не по алфавиту, а по реальному вкладу (хотя бы приблизительно). Вклад Евгения Желтоножского не сравним со вкладом кого-то еще в списке, скажем так. 

Но это можно в следующий раз.

2021-12-15 14:46 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
Это мы пустым пока оставляем?

2021-12-15 14:46 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l9.md
> +-
Это мы пустым пока оставляем?

2021-12-15 14:46 UTC, Yorko commented on qmlcourseRU/book/qcalgo/quantum_teleportation.md
> +-
Это мы пустым пока оставляем?

2021-12-15 14:48 UTC, Yorko approved these changes
Пара статей пока без авторов, но это мелочь, почти наверное там автор – Котенков Игорь

2021-12-15 14:54 UTC, alexey-pronkin commented
> @alexey-pronkin что тут делает #339? этот pr о другом. давай делать правильно: на каждую задачу отдельный pr (тут не тот случай, когда задачи можно объединить)

А так хотелось бы, иначе потом придется конфликт мерджить, там буквально изменение пары символов. Можешь тогда откатить

2021-12-15 15:32 UTC, vtrokhymenko commented on qmlcourseRU/book/authors.md
> +- [Бажанов Дмитрий](https://github.com/dbazhanov)
думал об этом, возможно стоит разделить этот список на две части, скажем, скамья джедаев и уверенные авторы (ну или что-то на подобии), а то мне сложно некоторых товарищей правильно отсортировать

но не факт что норм решение. если сейчас решим как, то переделаю, ибо создаем новую задачу

2021-12-15 15:32 UTC, polyzer commented on qmlcourseRU/book/qcalgo/quantum_teleportation.md
> +-
Моя

2021-12-15 15:33 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
нет, это значит что мне сложно твердо написать кто это делал, но указать нужно кто это

2021-12-15 15:33 UTC, vtrokhymenko commented on qmlcourseRU/book/qcalgo/quantum_teleportation.md
> +-
https://github.com/SemyonSinchenko/qmlcourse/pull/343#discussion_r769740009

2021-12-15 15:34 UTC, vtrokhymenko commented
> > @alexey-pronkin что тут делает #339? этот pr о другом. давай делать правильно: на каждую задачу отдельный pr (тут не тот случай, когда задачи можно объединить)
> 
> А так хотелось бы, иначе потом придется конфликт мерджить, там буквально изменение пары символов. Можешь тогда откатить?

пока оставим как есть, но в будущем не делай так

2021-12-15 15:44 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
@stalkermustang посмотри пж лекции по python и укажи правильных авторов, а то после переименования части файлов по блоку, сложно вспомнить кто именно писал лекцию

2021-12-15 17:58 UTC, meandmytram approved these changes

2021-12-15 20:02 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
@vtrokhymenko 7-8 лекции блока питон (дикты + функции) делала Саша @alexmorphine, остальные я + я бы ко второй лекции добавил @dkorzhov :) как человека, который собственно всю установку подготовил.  Соотв. 9+10 указываем меня.

2021-12-15 20:08 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
спасибо. будь добр, сделай push

2021-12-15 20:15 UTC, SemyonSinchenko approved these changes

2021-12-15 22:01 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
```suggestion
- [Котенков Игорь](https://github.com/stalkermustang)
```

2021-12-15 22:02 UTC, Yorko commented on qmlcourseRU/book/pythonblock/python_l9.md
> +-
```suggestion
- [Котенков Игорь](https://github.com/stalkermustang)
```

2021-12-16 07:02 UTC, alexey-pronkin commented on qmlcourseRU/book/authors.md
> +- [Бажанов Дмитрий](https://github.com/dbazhanov)
Можно отдельно выделить в порядке важности тех, кто глобально за что-то отвечает, как это сделано в practical rl https://github.com/yandexdataschool/Practical_RL#course-staff

2021-12-16 10:04 UTC, vtrokhymenko commented on qmlcourseRU/book/authors.md
> +- [Бажанов Дмитрий](https://github.com/dbazhanov)
а кого поставить выше тогда, если сделали одно и то же: написали лекцию и смотрели иные?

2021-12-16 10:19 UTC, merged

2021-12-16 10:25 UTC, Carinetta commented
Привет @vtrokhymenko!
- Саймон
- квантовая телепортация
- HHL
- QAOA

2021-12-16 10:30 UTC, vtrokhymenko commented
> Привет @vtrokhymenko!
> 
> * Саймон
> * квантовая телепортация
> * HHL
> * QAOA

спасибо. везде были указаны, помимо телепортации, правки уже внес в master

2021-12-16 11:11 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
@Yorko я тут посмотрел, ты, выходит, уже сделал, и мне ничего делать не надо? в Python-блоке во всех леках появились авторы.

2021-12-16 11:36 UTC, vtrokhymenko commented on qmlcourseRU/book/pythonblock/python_l8.md
> +-
по python блоку всё дописали где нужно и уже на передовой