Feature/high order gradients
SemyonSinchenko/qmlcourse pull request #52
Opened 2021-06-08 14:47 UTC by SemyonSinchenko

Это лекция продвинутого уровня. Тут градиенты чуть более детально.

_Замечание_
Я сразу замержил сюда лекцию по SVM и PR с рарскраской цевтов оглавления, чтобы потом не разруливать конфликты. Мне просто так удобнее было + я хотел смотреть на результат "в целом". Если какой-то из упомянутых PR все еще не будет в мастере к моменту, как будем мержить это - я все откачу как сейчас в мастере - тут без вопросов.

Так что ревьюим только саму лекцию, остальное перед мержем посмотрим.

2021-06-08 16:27 UTC, karelin commented
Какая у нас будет политика по статьям?
Я бы предложил стараться везде ставить ссылки на arXiv (если есть или на URL для открытого доступа). И на мой взгляд нет смысла дублировать URL и DOI.

2021-06-08 16:31 UTC, SemyonSinchenko commented
> Какая у нас будет политика по статьям?
> Я бы предложил стараться везде ставить ссылки на arXiv (если есть или на URL для открытого доступа). И на мой взгляд нет смысла дублировать URL и DOI.

Если честно, то я просто копипастил BibTex из google scholar... То есть DOI оставлять, а в URL где возможно ставить arXiv?

2021-06-08 16:49 UTC, karelin commented
Да, DOI оставлять и желательно восстанавливать если GS это съел. В URL - arxiv или другой источник PDF. Будет в разы удобнее. Если успею, эти три могу завтра сделать.

2021-06-08 16:54 UTC, SemyonSinchenko commented
> Да, DOI оставлять и желательно восстанавливать если GS это съел. В URL - arxiv или другой источник PDF. Будет в разы удобнее. Если успею, эти три могу завтра сделать.

Было бы очень круто, спасибо! Я так глубоко не вникал никогда)
По всем новым ссылкам тогда буду проверять корректность того, что выплюнул GS)

2021-06-08 17:14 UTC, karelin requested changes
Просмотрел, думаю надо немного дополировать, исправить опечатки и немного стиль.

В целом понравилось.

2021-06-08 17:14 UTC, karelin commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +Поскольку обычно нам интересны многомерные пространства, то точки там превращаются в вектора. Также оказыается, что построение такой разделяющей плоскости зависит не от всех точек (векторов), а тольк
Опечатка, в слове "оказывается"

2021-06-08 17:14 UTC, karelin commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +- В реальности нам интересны не все точки, а лишь те, которые лежат вблизи разделяющей прямой
Я бы везде писал гиперплоскость (а для 2-мерного случая - прямая). 2D - это практически вырожденный случай.

2021-06-08 17:14 UTC, karelin commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +- Решение задачи квадратичного программирования може быть получено аналитически
Опечатка, може -> может

2021-06-08 17:14 UTC, karelin commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +Как мы много говорили в более ранних лекциях, квантовые схемы позволяют нам оперировать в Гильбертовых пространствах волновых функций. Эти пространства имеют экспоненциально большую размерность, при
Как и гессиан, гильбертово пространство - с малой буквы.

2021-06-08 17:14 UTC, karelin commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +### Преобразование состояния
Этот раздел выглядит очень "рваным" - не сильно связано с предыдущим текстом и слишком коротко, ИМХО

2021-06-08 17:14 UTC, karelin commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +Мы не будем сами с нуля писать решение задачи квадратичного программирования. Мы воспользуемся готовой рутиной из `scikit-learn`. Используемая там реализация позволяет вместо ядерной функции передать
Может лучше ссылку сюда: https://ru.wikipedia.org/wiki/%D0%9E%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C_%D0%93%D1%80%D0%B0%D0%BC%D0%B0

2021-06-08 18:12 UTC, SemyonSinchenko commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +Мы не будем сами с нуля писать решение задачи квадратичного программирования. Мы воспользуемся готовой рутиной из `scikit-learn`. Используемая там реализация позволяет вместо ядерной функции передать
В рус-вики именно определитель матрицы Грама, а не сама матрица. Боюсь собьет с толку...

2021-06-08 18:12 UTC, SemyonSinchenko commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +### Преобразование состояния
Поправил

2021-06-08 18:12 UTC, SemyonSinchenko commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +Как мы много говорили в более ранних лекциях, квантовые схемы позволяют нам оперировать в Гильбертовых пространствах волновых функций. Эти пространства имеют экспоненциально большую размерность, при
Поправил

2021-06-08 18:12 UTC, SemyonSinchenko commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +- Решение задачи квадратичного программирования може быть получено аналитически
Поправил

2021-06-08 18:12 UTC, SemyonSinchenko commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +- В реальности нам интересны не все точки, а лишь те, которые лежат вблизи разделяющей прямой
Поправил

2021-06-08 18:13 UTC, SemyonSinchenko commented on qmlcourseRU/book/qsvmblock/hybridsvm.md
> +Поскольку обычно нам интересны многомерные пространства, то точки там превращаются в вектора. Также оказыается, что построение такой разделяющей плоскости зависит не от всех точек (векторов), а тольк
Поправил

2021-06-08 18:13 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +Внимательно взглянув на выражение для 2-х производных можно заметить, что оптимизация там возможна при рассчете диагональных элементов Гессиана. Давайте выпишим выражение для диагонального элемента я
Поправил

2021-06-08 18:13 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +Но чаще всего нам необходимо не просто посчитать Гессиан, а еще и посчитать Градиент, так как в большинстве методов 2-го порядка требуются оба эти значения. В этом случае хочется попробовать подобрат
Поправил

2021-06-08 18:13 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +где $H$ -- матрица такая, что $H^2 = \mathbf{1}$. Другой возможный вариант записи -- представить матрицу $H$ как линейную комбинацию операторов Паули $\sigma^x, \sigma^y, \sigma^z$.
Поправил

2021-06-08 18:13 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +В этой лекции мы посмотрим на ту математику, которая лежит "под капотом" у _parameter-shift rule_. Мы познакомимся с обобщением _parameter shift_, а тТакже мы увидим, как можно оптимизировать этот ме
Поправил

2021-06-09 13:46 UTC, karelin commented
> Было бы очень круто, спасибо! Я так глубоко не вникал никогда)
> По всем новым ссылкам тогда буду проверять корректность того, что выплюнул GS)

Сделал

2021-06-09 13:50 UTC, karelin approved these changes
Все хорошо, желательно чтобы еще кто-то просмотрел, особенно по формулам

2021-06-10 13:30 UTC, Yorko requested changes
Сюда как-то попали лекции про SVM, нужно аккуратнее смержить. 

Хотелось бы пример на PennyLane, как [тут](https://pennylane.ai/qml/demos/tutorial_backprop.html) – иначе очень сложно воспринимать. 

Я был с этим всем знаком по QHack, но все равно лень продираться через математику, формулы не ревьюил. 

В целом хотелось бы более явной мотивации, зачем это все. Условно, почему простой BFGS не пойдет. Я бы на этой статье отвалился – вернулся бы обратно в "зеленый трек".

2021-06-10 13:30 UTC, Yorko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +Видно, что мы хотим считать производную не от самой параметризованной схемы $U_{j...k}$, а от наблюдаемой. Для тех, кто забыл, что такое _наблюдаемая_, рекомендуем вернуться к лекции про кубит. Если
>> рекомендуем вернуться к лекции про кубит

Ссылки между лекциями как будут работать? Сюда бы ее

2021-06-10 13:30 UTC, Yorko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +$$
Может, я туплю, но $\hat{M}$ – это оператор измерения наблюдаемой. А что тогда есть матрица M?

2021-06-10 13:35 UTC, Yorko commented
Иконки с цветом лекций – 🔥 вроде просто, а очень оживляет

2021-06-10 16:43 UTC, Randl commented on qmlcourseRU/book/gradsblock/hogradients.md
> +где $H$ -- эрмитова матрица ($HH^\dagger = \mathbf{1}$). Другой возможный вариант записи -- представить матрицу $H$ как линейную комбинацию операторов Паули $\sigma^x, \sigma^y, \sigma^z$.
Эрмитова значит что $H=H^\dagger$. В статье ограничиваются "rotation-like" операторами ($H^2=1$), и говорят что для общего гейта можно либо разложить $U$ на вращения, либо расписать общий эрмитов оператор в базисе Паули и использовать чуть более сложную схему для получения градиентов по каждому коеффициенту.

2021-06-10 17:03 UTC, Randl commented on qmlcourseRU/book/gradsblock/hogradients.md
> +Можно заметить, что, например, использование $s = \frac{\pi}{4}$ для гессиана, а также "стандартного" $s=\frac{\pi}{2}$ для градиента позволит полностью переиспользовать в диагональных элементах гесс
Возможно стоит упомянуть что диагональ гессиана может быть использована без полного гессиана для diagonal Newton optimizer

2021-06-10 19:14 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +$$
Это и есть наблюдаемая. M это просто оператор, который мы измеряем. Так устроена физика, что любому эрмитову оператору соответствет какая-то физическая величина, которую можно мерить.

2021-06-11 10:43 UTC, Yorko commented
По моим комментам все норм. Только воскрешу еще раз аргумент про PennyLane – может, сюда все же пример с кодом добавить? Например, разбор аналогичной задачи на QHack.

2021-06-11 10:48 UTC, SemyonSinchenko commented
> По моим комментам все норм. Только воскрешу еще раз аргумент про PennyLane – может, сюда все же пример с кодом добавить? Например, разбор аналогичной задачи на QHack.

Сегодня сделаю. Поправлю формулы, немного раскрою мотивацию и идея про диагонального ньютона хороша - наверное стоит это закодить. Надо просто сейчас чуть-чуть поработать на капиталистов, а то меня уволят)

2021-06-12 09:56 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +Видно, что мы хотим считать производную не от самой параметризованной схемы $U_{j...k}$, а от наблюдаемой. Для тех, кто забыл, что такое _наблюдаемая_, рекомендуем вернуться к лекции про кубит. Если
Сделал

2021-06-12 09:57 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +\bra{U_i(\theta_i)\Psi}\hat{M}\ket{U_i(\theta_i)\Psi} = \hat{A} + \hat{B}\cos{\theta_i} + \hat{C}\sin{\theta_i}
Добавил

2021-06-12 09:57 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +где $H$ -- эрмитова матрица ($HH^\dagger = \mathbf{1}$). Другой возможный вариант записи -- представить матрицу $H$ как линейную комбинацию операторов Паули $\sigma^x, \sigma^y, \sigma^z$.
Поправил

2021-06-12 09:57 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +Можно заметить, что, например, использование $s = \frac{\pi}{4}$ для гессиана, а также "стандартного" $s=\frac{\pi}{2}$ для градиента позволит полностью переиспользовать в диагональных элементах гесс
Добавил упоминание

2021-06-12 09:58 UTC, SemyonSinchenko commented
> По моим комментам все норм. Только воскрешу еще раз аргумент про PennyLane – может, сюда все же пример с кодом добавить? Например, разбор аналогичной задачи на QHack.

Было бы круто, но у меня нет сейчас сил кодить квази Ньютона самому. Пример простого parameter shift есть в базовой лекции про градиенты. Идея крутая, но не приоритетная. Предлагаю завести задачу на то, чтобы закодить что-нибудь второго порядка и показать что вау, оно сходится быстрее. А пока смержить так.

2021-06-12 10:31 UTC, Yorko approved these changes

2021-06-13 06:10 UTC, Randl commented on qmlcourseRU/book/gradsblock/hogradients.md
> +\frac{\partial \langle M \rangle}{\partial \theta_i} = -\frac{i}{2}Tr(M U_{k, ..., i}[P_i, U_{i-1, ..., 1}\Psi_i U_{i-1, ..., 1}^\dagger]U_{k, ..., i}^\dagger)
Опять таки если базовый matrix calculus (вида d Tr(AX)/dX = A^T) есть в интро, стоит сослаться

2021-06-13 06:56 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +G_i = \frac{\partial \bra{U_{j...k}\Psi}\hat{M}\ket{U_{j...k}\Psi}}{\partial \theta_i}
Я везде так пишу (как-то исторически так сложилось и мне кажется так понятнее). Если менять то везде. Заведу задачку на подумать.

2021-06-13 06:56 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +U_i = e^{-\frac{i}{2}P_i\theta_i}
И правда, пусть будут просто Паули-like операторы и все. Без обобщений.

2021-06-13 06:56 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +\langle M(\theta) \rangle = Tr(M U_{k, ..., 1} \Psi_i U_{k, ..., 1}^\dagger)
Спасибо, это реально затуп с моей стороны.

2021-06-13 06:57 UTC, SemyonSinchenko commented on qmlcourseRU/book/gradsblock/hogradients.md
> +\frac{\partial \langle M \rangle}{\partial \theta_i} = -\frac{i}{2}Tr(M U_{k, ..., i}[P_i, U_{i-1, ..., 1}\Psi_i U_{i-1, ..., 1}^\dagger]U_{k, ..., i}^\dagger)
Будет лекция про Mixed states, там будет это. Лекци пока в разработке - ссылка будет, добавлю сюда.

2021-06-13 07:12 UTC, Randl approved these changes

2021-06-13 10:29 UTC, merged