Added button and action on PR
SemyonSinchenko/qmlcourse pull request #54
Opened 2021-06-09 16:02 UTC by dkorzhov

2021-06-09 19:36 UTC, vtrokhymenko commented
@dkorzhov а зачем пустой файл `.nojekyll`?

2021-06-09 20:15 UTC, SemyonSinchenko requested changes
@dkorzhov Огромное спасибо за эту штуку! Добавь себя пожалуйста в https://github.com/SemyonSinchenko/qmlcourse/blob/master/qmlcourseRU/book/authors.md, там после раздела "Основные ревьюеры" создай раздел "Техническая поддержка" или что-то такое и добавь туда себя.

2021-06-09 20:25 UTC, SemyonSinchenko commented
Оно сейчас падает просто потому, что надо сначала смержить, да?

2021-06-09 20:51 UTC, dkorzhov commented
> а зачем 2й раз повторять одно и то же, то бишь в 13й строке такое же

это один из вариантов реализации, это разные ветки качаются в локальную папку.
кэш сейчас сохраняется в ветку gh-pages, я его забираю в локальную папку и после этого делаю build книги, которая видит кэш.
еще как вариант можно в основную ветку заливать изменения после билда книги.

2021-06-09 20:53 UTC, dkorzhov commented
> Оно сейчас падает просто потому, что надо сначала смержить, да?

Сейчас падает, потому что не хватате прав на выполнение в этом репозитории. Надо проверить в настройках разрешения на github actions, в том числе на доступ к чтению и записи прав.
  remote: Permission to SemyonSinchenko/qmlcourse.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/SemyonSinchenko/qmlcourse.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"

2021-06-09 21:01 UTC, dkorzhov commented
> @dkorzhov а зачем пустой файл `.nojekyll`?

надо будет наверное в .gitignore прописать файлы и папки. Он автоматом создается при билде книги. Это я видимо когда тестировал запись в тот же репозиторий, он туда попал и я его не заметил.

2021-06-10 03:36 UTC, SemyonSinchenko approved these changes

2021-06-10 03:56 UTC, SemyonSinchenko commented
> надо будет наверное в .gitignore прописать файлы и папки.

А ты можешь удалить его из реквеста сейчас? Ну и сразу добавить в gitignore другие артифакты книги.

2021-06-10 06:10 UTC, dkorzhov commented
> > надо будет наверное в .gitignore прописать файлы и папки.
> 
> А ты можешь удалить его из реквеста сейчас? Ну и сразу добавить в gitignore другие артифакты книги.

Готово, .gitignore пока не трогал, там надо отдельно будет смотреть

2021-06-10 09:27 UTC, merged