Python Intro lec1 (about python)
SemyonSinchenko/qmlcourse pull request #70
Opened 2021-06-14 21:47 UTC by stalkermustang

2021-06-15 11:05 UTC, SemyonSinchenko approved these changes

2021-06-15 12:20 UTC, Yorko commented
Годно! Стиль тоже нравится, радует, что изложение грамотное. 

Можно добавить, что питон хорош именно для ML и QML, так как мы на этом в дальнейшем акцент делаем. 

Еще я бы оживил картинками. Например, говоришь 
> Нашли и скачали библиотеку, которая позволяет провести вычисления, о которых в прошлом веке можно было лишь мечтать, за один вечер
- и тут можно вставить картинку, скажем, про CFD и моделирование аэродинамики болида, условно – все чисто на питоне. 

То есть в целом классно, читается, как блогпост, но картинок не хватает.

2021-06-15 12:21 UTC, Yorko commented
Аппрувить пока рано имхо, если мы не планируем часть лекции, самое начало, комитить в мастер

2021-06-15 12:46 UTC, stalkermustang commented
>Аппрувить пока рано имхо, если мы не планируем часть лекции, самое начало, комитить в мастер
@Yorko а можно прям в эту ветку 2-3-n лекции заливать? я думал 1 ветка = 1 лекция. Именно вводная (до установки и введения в jupyter) это всё (ну картинки добавлю по твоим заветам + еще пару ссылок хотел прикрепить).

2021-06-15 13:08 UTC, SemyonSinchenko commented
> @Yorko а можно прям в эту ветку 2-3-n лекции заливать? я думал 1 ветка = 1 лекция. Именно вводная (до установки и введения в jupyter) это всё (ну картинки добавлю по твоим заветам + еще пару ссылок хотел прикрепить). 

Замержи сюда мастера, а то тут CI/CD старый.

2021-06-16 04:25 UTC, sharthZ23 commented
Круто, мне зашло. Я только бы добавил кликабельные ссылки в интересных фактах:
- PEP - https://www.python.org/dev/peps/
- Zen of python - https://www.python.org/dev/peps/pep-0020/ | https://tyapk.ru/blog/post/the-zen-of-python
- PyPI - https://pypi.org/
- Зарепортить баг - https://bugs.python.org/
- Предложить идею для языка - https://mail.python.org/archives/list/python-ideas@python.org/

2021-06-20 11:43 UTC, karelin requested changes

2021-06-20 11:43 UTC, karelin commented on qmlcourseRU/book/pythonblock/python_l1.md
> +### И в чем подвох?
Я бы еще здесь **обязательно** написал, что Python - _интерпретируемый_ язык, к тому же с динамической типизацией, и поэтому крайне медленный. Настоящая сила Python - в том, что это "язык-клей", который обеспечивает удобный доступ к различным библиотекам, которые уже написаны на высокоэффективных языках (C/C++, Fortran, CUDA C, ...). 

Но в целом надо иметь в виду, что очень нежелательно в самом коде на Python делать длинные (особенно вложенные) циклы, а вызывать соответствующие функции из сторонних библиотек, например `np.sum()`, или использовать специальные средства, типа `Cython` или `Numba`.

2021-07-13 22:15 UTC, stalkermustang commented on qmlcourseRU/book/pythonblock/python_l1.md
> +### И в чем подвох?
Добавил про интерпретируемость. Про динамические типы напишу в лекции про типы, сделав референс к первой лекции - сейчас ЦА, кажется, может это не понять, равно как и про "длинные циклы" и "вызов библиотек". В местах возникновения удобных ситуаций обязательно упомяну.

2021-07-17 08:08 UTC, Yorko approved these changes

2021-07-17 08:21 UTC, SemyonSinchenko approved these changes

2021-07-17 08:35 UTC, merged