Deutsch's algorithm - начало
SemyonSinchenko/qmlcourse pull request #75
Opened 2021-06-23 00:45 UTC by doktrster

2021-06-23 05:14 UTC, SemyonSinchenko requested changes
Добавь изменения в toc, а то сейчас билд цспешный, но файл не отображается в оглавлении.

P.S. Пока ревьюеры могут смотреть тут:
https://semyonsinchenko.github.io/qmlcourse/_build/html/book/qcblock/deutschs_algorithm.html

2021-06-24 21:07 UTC, SemyonSinchenko commented
А код будет? Все же "зеленая" лекция...
И еще, может в середине чуть-чуть "разбавить"? Например, сделать note, что Дойч не только физик, но и автор книжек о том, как устроен мир? Ну либо что-то такое, чтобы немного давать читателю возможность передохнуть?

2021-06-25 14:49 UTC, SemyonSinchenko commented on qmlcourseRU/book/qcblock/deutschs_algorithm.md
> +
Как вариант - сделать
```{note}
текст про Дойча
```

Оно тогда как в лекции про свм будет смотреться: https://semyonsinchenko.github.io/qmlcourse/_build/html/book/qsvmblock/hybridsvm.html

2021-06-25 15:31 UTC, SergeiShirkin commented on qmlcourseRU/book/qcblock/deutschs_algorithm.md
> +
Я добавил про Дойча. Насчет кода тоже хорошая идея, скоро напишу

2021-06-27 10:46 UTC, SemyonSinchenko commented
@SergeiShirkin ты сначала напишешь код, или сначала смержии, а код потом? Напиши тогда тут, как полностью закончишь. В целом я готов мержить.

2021-06-28 09:04 UTC, SergeiShirkin commented
Можно замержить уже сейчас

2021-06-29 05:33 UTC, SemyonSinchenko approved these changes

2021-06-29 05:34 UTC, merged

2021-06-29 20:52 UTC, SergeiShirkin commented
@SemyonSinchenko Кстати, насчет кода - на чем лучше написать? Студенты к этому времени еще не будут знать PennyLane и Qiskit, только Numpy. Что на этот счет думаешь?

2021-06-30 04:47 UTC, SemyonSinchenko commented
Пиши на Pennylane. Там уже были примеры в лекции про гейты. Но если сможешь на чистом Numpy то тоже вариант)

2021-07-05 22:38 UTC, meandmytram commented
`Задача Дойча (в английском варианте - Deutsch’s algorithm)` -- все-таки задача и алгоритм это разные вещи. Я, наверное, прикапываюсь сильно, но мне кажется, у человека, читающего это с нуля, возникнет недоумение. Может быть, написать `Deutch's problem`?

В остальном лекция просто супер, мне кажется, самое то для этого курса, спасибо!

2021-07-06 12:27 UTC, SergeiShirkin commented
Да, действительно, несоответствие. Я делал как в курсах СПбГУ на Coursera. У них русском варианте - задача, а в английском - алгоритм. Наверное, лучше называть как алгоритм, потому что в google больше страниц выдает и на русском, и на английском, да и студентам-программистам так понятнее будет. Сегодня поменяю